### ISSUE TITLE
Serverless changing DateTimeOffset value timezones

### ISSUE THREAD

**Issue by andrew-tevent** [Azure/azure-signalr#1468] opened 2021-10-19 10:38 UTC
### Describe the bug
When sending messages from a Functions backend to SignalR serverless, which contain `DateTimeOffset` timestamps, the messages are arriving at the Client having had their Offset changed.

![image](https://user-images.githubusercontent.com/78795042/137893276-b22c43af-42a0-48c2-b6c3-277a28e2a931.png)
(Am seeing the +8 hr timezone, which is not a timezone that any of my Function or App Services are running in)

### To Reproduce
Send a message to SignalR serverless which contains a DateTimeOffset value which has, for example, no Offset so is UTC.   Observe that the client receives the message with the Offset changed to a different Timezone.

This occurs whether sending the message via Azure Function Output Bindings, or using the Management SDK.

Logging the value of the DateTimeOffset before sending shows that it has the correct Timezone/Offset.

**Comment by Y-Sindo** [comment] 2021-11-02 11:05
Root cause found: The Newtonsoft deserializer changes the time zone to the local time zone of your Azure SignalR server. 

We know the best fix is to return to clients what you send, but it is a behaviour change and needs more inspection. If you don't need to preserve the origin offset, you could customize the deserializer in the client side as a mitigation.

We will continue to look at this issue.

**Comment by andrew-tevent** [comment] 2021-11-02 11:25
@Y-Sindo Thanks for the update.  

We aren't currently affected by it because we convert to the receiving client's timezone - but we will soon require preservation of the original timezone, otherwise we would have to send that in an additional property on the payload (as an integer/timespan) which isn't ideal as it means more data being sent.

**Comment by Y-Sindo** [comment] 2021-12-27 07:40
@andrew-tevent The code to fix the issue in the service side is merged, but it will take about two months to be released. I will keep you updated in the future.

**Comment by talksoft999** [comment] 2022-03-31 11:02
@Y-Sindo We are still seeing the above issue in our environment. Can you confirm if the code has been released and if so what action is required on our part to see the fix.

**Comment by Y-Sindo** [comment] 2022-04-01 05:27
@talksoft999 The code is reverted due to some problems in the last release. The problem is fixed now and hopefully, it can be released in this release cycle. I will notify you once it is really released.

**Comment by oatsoda** [comment] 2022-04-28 07:23
@Y-Sindo This looks like it is fixed now, so assume this has been released?

![image](https://user-images.githubusercontent.com/3919587/165699227-3dc78a85-3e8d-47c8-97ac-b54a4510d7c0.png)

And just to confirm, does it do any processing on the Date at all?  Wondering if it might still be converting to UTC?

**Comment by Y-Sindo** [comment] 2022-05-16 06:17
@oatsoda The fix has been applied to all the regions.

**Closed by Y-Sindo** 2022-05-16 06:17 UTC
