### ISSUE TITLE
Connections dropping every day

### ISSUE THREAD

**Issue by fabiano** [Azure/azure-signalr#420] opened 2019-02-28 21:16 UTC
I'm creating this new issue because I'm not sure if it's the same problem happening on the issue https://github.com/Azure/azure-signalr/issues/402.

Two or three times per day our logs are flooded with error messages related to the Azure SignalR service.

Checking the Metrics page, we saw that at the same time the number of connections drops. Then the connections begin to increase again.

![53377832-2f8e7200-3942-11e9-948c-1bb74ec70f49](https://user-images.githubusercontent.com/2686/53598757-4a502900-3b84-11e9-9376-48920178c35b.png)

And we are not seeing any error on the client side.

These are the error messages:

```
15:52:46.808 [53] ERR Microsoft.Azure.SignalR.ServiceConnectionBase -> Connection e34eab1c-34bf-46fb-bc07-31d2843fa0fb to the service was dropped.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()
```

```
15:53:13.358 [73] ERR Microsoft.Azure.SignalR.ServiceConnection -> Error while sending message to the service.
Microsoft.Azure.SignalR.Common.ServiceConnectionNotActiveException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
```

```
15:53:15.870 [197] ERR Microsoft.Azure.SignalR.ServiceConnectionBase -> Service timeout. 30000.00ms elapsed without receiving a message from service.
```

```
15:53:31.865 [182] ERR Microsoft.Azure.SignalR.ServiceConnectionBase -> Error receiving handshake response.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnectionBase.<ReceiveHandshakeResponseAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SignalR.ServiceConnectionBase.<HandshakeAsync>d__56.MoveNext()
```

Today, we saw two new messages when the connections dropped:

```
16:21:02.385 [124] ERR Microsoft.Azure.SignalR.ServiceConnection -> Error while sending message to the service.
System.InvalidOperationException: Internal server error.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
```

```
16:21:02.284 [40] ERR Microsoft.Azure.SignalR.ServiceConnection -> Error while sending message to the service.
System.InvalidOperationException: Internal server error.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.<WriteAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SignalR.ServiceConnection.<ProcessOutgoingMessagesAsync>d__14.MoveNext()
```

Versions:

- JavaScript client: 1.1.2
- Microsoft.AspNetCore.SignalR: 1.1.0
- Microsoft.Azure.SignalR: 1.0.6

**Comment by vicancy** [comment] 2019-03-01 03:49
Could you email me your instance name and subscription id for me to check the service side log?

**Comment by fabiano** [comment] 2019-03-01 16:24
@vicancy Just sent to you the email

**Comment by jsheetzati** [comment] 2019-03-01 18:21
We are also seeing this error in our app service logs. I will email our app instance name if you do not mind taking a look at it too, @vicancy

**Comment by MrPipa** [comment] 2019-03-04 11:28
I have a web application in production and cannot suddenly connect to our SignalR service at all.
Wonder if this could be related?

**Comment by bmahloch** [comment] 2019-03-06 13:33
We started seeing this same error on 2/28/2019. There were no changes made to the environment. It's been happening 3 - 5 times per day and forces us to restart our AppService to reconnect.

We are currently working on a patch that will isolate all the signalr related startup into its own function with the hope that we can "self-heal" these drops without interrupting user sessions.

Is there any quick configuration/startup change that may help keep this connection stable in the meantime? 

Happy to provide more details if it helps troubleshoot.

**Comment by vicancy** [comment] 2019-03-07 04:21
We’ve identified an issue in our load-balancer that it reloads frequently which leads to persistent connections drop. We’ve rolled out the hotfixes to all the impacted instances.

**Comment by fabiano** [comment] 2019-03-07 15:14
@vicancy We are not seeing errors in our logs anymore. Thank you again for your help.

**Comment by vicancy** [comment] 2019-03-11 02:51
I am closing the issue. Please reopen it when there are still issues.

**Closed by vicancy** 2019-03-11 02:51 UTC

**Comment by jasonkirby** [comment] 2019-03-13 20:43
@vicancy We're seeing the same Microsoft.Azure.SignalR.Common.ServiceConnectionNotActiveException errors from the host app communication to the Azure SignalR service periodically (and most of the other error messages noted above are recorded by the clients connected to the host).  We just had 2 events in the last hour that dumped all the connections off.  Did the hotfixes that were made apply to everyone, or only those complaining of the issue noted here?

Version
Microsoft.Azure.SignalR 1.0.6

**Comment by vicancy** [comment] 2019-03-14 07:29
@jasonkirby All the influenced instances should be patched already. Would you minding sending me your instance name for a check?

**Comment by jasonkirby** [comment] 2019-03-15 14:28
@vicancy I sent you an email yesterday with the requested info.

**Comment by jasonkirby** [comment] 2019-03-19 13:53
@vicancy Errors are ongoing.  Did you need any further info?

**Comment by vicancy** [comment] 2019-03-20 03:24
Hi Jason @jasonkirby , I noticed that all your server connections came from one app server. Could you check if there were any events took place from app server side such as app server restart, IIS recycle, high CPU usage, etc? When server connection drops, client will experience connection drops.

I looked into the latest events of your instance. I can see twice all server connection drops on 2019-03-18,  which were 2019-03-18T11:23:26 and 2019-03-18T23:24:58, and once on 2019-03-19 at 01:28:21 UTC.

From our log, we can see that:
1. 2019-03-18T11:23:26: all server connections don't receive heartbeat from app server side and closed the server connection. Doubt if it is caused by app server side.
2. 2019-03-18T23:24:58: internally we experience short network connectivity issue connecting to internal service. Should be recovered very soon.
3. 2019-03-19T01:28:21, one of our internal service was doing OS patching which can cause server connection drops. Should be recovered very soon.

As the connections between client and Service, and between AppServer and Service are persistent connections, they may experience network connectivity issues. In the Server SDK, we have “Always Reconnect” strategy to server connections. As the best practice, we also encourage users to add continuous reconnect logic to the clients with a random delay time to avoid massive simultaneous requests to the server.
The Load Balancer related instability should have been fully addressed, on regular basis there are service new version releases, and sometimes the Azure wide OS patching or upgrades or occasionally our dependent services’ interruption. These may bring in a very short period of service disruption, but as long as client side has the disconnect/reconnect mechanism, the impact is minimal like any client-side caused disconnect-reconnect.
If you have very strict availability requirement scenarios, we can further discuss about your specific service and scenarios, and what we can do to help.

**Comment by jasonkirby** [comment] 2019-03-20 19:15
Hi @vicancy , 

Regarding number 1, I'm not seeing anything in the Application insight logs / metrics of the App server at that time, perhaps I'm not looking in the right place or right way.

The clients do have reconnection code and will typically recover on their own.  I do need to get the random time delay added back in however as I lost that with some refactoring I did a couple weeks back.

The host app server is catching the Microsoft.Azure.SignalR.Common.AzureSignalRNotConnectedException in the Serilog entries recorded to Azure Log Analytics (not from one of my logging statements, something automatically being logged by the addition of Serilog), but I'm not certain if the clients are realizing that they need to reconnect for a period of time after one of those events.  I'd like to catch that exception myself and manually inform the clients to reconnect.  I just need to figure out where to catch that exception in the app server code to notify them.

We had a new issue overnight where at around 9AM UTC the SignalR service dropped all connections and was still that state when I came into work 5.5 hours later.  Our app server logged almost 31K AzureSignalRNotConnectedException during that time while the clients were trying to reconnect.  I ended up restarting the SignalR service and the app server to get it going again. 

Could you look into the logs on your end to see if you can tell what may have occurred there?  That's the first time anything like that has happened.  All other issues previously noted have been transient.  

'Server timeout (30000.00ms) elapsed without receiving a message from the server' errors are the other thing we've been seeing more of lately.

We develop a point of sale legacy application that we have lifted and shifted to the cloud (running in RDS) that the SignalR tech is being used to communicate between that and an on prem application handling local hardware devices performing things like integrated credit card processing and barcode scanning.  Any extended periods of downtime leave our customers potentially unable to operate their business and are very impacting to them.  

Transient failures are unavoidable of course, but we're trying to minimize them and automatically recover as quickly as we can.  We're still in the initial roll out phase for the solution to a limited number of customers.

Your help is greatly appreciated.

Thanks

**Comment by vicancy** [comment] 2019-03-21 02:59
Hi @jasonkirby We are actively investigating the issue, will let you updated once we have any findings.

**Comment by vicancy** [comment] 2019-03-21 03:32
Hi @jasonkirby is there any other connection related errors observed from your app server side during that 5.5 hours? AzureSignalRNotConnectedException happens when client negotiates with app server however app server finds no server connections available.

Could you help to verify that 
1. within these 5.5 hours, is there any log indicating that the SDK is trying to reconnect to the Azure Service? In our SDK, we have logic that SDK should always reconnect at most every 1 minute, if it is not reconnecting, there must be a bug in our SDK's reconnect logic.
2. If SDK is always trying to reconnect, could you provide the error message why the connection failed to establish? We don't find any server connection logs from the service side during that period.

Or you can provide us logs within the 5.5 hours for us to investigate.

**Comment by jasonkirby** [comment] 2019-03-21 18:15
Hi @vicancy I have sent you an email with a zipped CSV dump of the log tables from that 5.5 hour time period.

Let me know if you need anything else, or if there is some specific logging that I have missed.

Thanks

**Comment by jasonkirby** [comment] 2019-03-21 19:52
@vicancy I just sent another email containing the local client exceptions from the HubConnection.Closed event handler.  I just realized I had those filtered out in the previous custom log dump and they may be useful.

**Comment by johnjbateman** [comment] 2019-04-24 14:43
Also experiencing this issue in #497
