### ISSUE TITLE
Clients in one geographic region unable to maintain connections until service restarted via portal

### ISSUE THREAD

**Issue by BinarySo1o** [Azure/azure-signalr#428] opened 2019-03-08 01:11 UTC
We experienced an issue starting ~17:20 UTC where javascript clients in one geographic region experienced intermittent timeouts when negotiating and starting connections. When these clients were able to connect, they would disconnected almost immediately with a message of "Internal server error." 

System errors were observed in the metrics for the service leading us to restart it at 19:26, resolving the issue.
![image](https://user-images.githubusercontent.com/25277056/54000136-9e2ab700-411c-11e9-83e8-3871752ade09.png)

Unfortunately, a rule creation failure warning is returned when creating an alert for this metric... 
If we could successfully create this alert, is there an api available that would allow us to restart the service programmatically? Can you clarify if the system error metric encompasses only signalR service issues, or could this also reflect a configuration issue we need to address?

**Comment by vicancy** [comment] 2019-03-11 03:44
"Internal server error" can be caused by Azure SignalR Service or app server side error. For both detailed errors are not exposed to client side. Could you email me your instance name and subscription id so that I can check if there were anything abnormal from service side?

**Comment by BinarySo1o** [comment] 2019-03-12 06:21
Requested information sent 👍

**Comment by vicancy** [comment] 2019-03-14 07:57
Looks like a bug for ASP.NET SignalR support that resources are not correctly disposed when exceptional cases take place. We are actively investigating the root cause and will get you updated once we have any findings.

**Comment by JialinXin** [comment] 2019-03-18 09:25
@BinarySo1o Looks all the failed requests have authentication failure which block connection creation. Would you check server trace if there's related logs?

**Comment by JialinXin** [comment] 2019-03-19 02:42
@BinarySo1o Would like to double check about the time? Is the incident around March 8th 17:00 PM UTC? The errors around that time are all client authentication failures which is marked as user errors. It's not matching the description. I'm wondering we're looking into wrong time range. Would you help check?

**Comment by JialinXin** [comment] 2019-04-08 09:06
@BinarySo1o It's been over a month and not getting a response. Are you still facing the errors?
@sobelito Saw your thumbs up and feel free to provide information if you have met similar problems.

**Comment by JialinXin** [comment] 2019-04-15 03:46
I'm closing this issue without any feedback for over a month. Feel free to open a new one and at me if you encounter similar problem in the future.

**Closed by JialinXin** 2019-04-15 03:46 UTC
Labels: bug
