### ISSUE TITLE
Hub Messages occasionally don't arrive

### ISSUE THREAD

**Issue by cnlogistics** [Azure/azure-signalr#160] opened 2018-08-14 01:55 UTC
Hello
I utilize an Azure SignalR Service on Standard S2 App Service Plan and the service itself on Standard price tier.

My Hub is hosted in an Asp.Net Core 2.1 (netstandard20) Api App in Azure.

I invoke the Hub action methods with the .Net Client v.1.0.2 from inside an Http Trigger Azure Function.

I frequently notice that my messages are properly sent ro the Hub but don't be transmitted to my WebApp.

Is there any diagnostic possibility in Azure SignalR Service AddAzureSignalR() method that can be configured?

Best
Eric

**Comment by vicancy** [comment] 2018-08-14 02:27
Hi @cnlogistics , you can set `EnableDetailedErrors = true` from the App Server side (https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-server-options), and also configure logging through `HubConnectionBuilder().ConfigureLogging` from client side (https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-logging).

Are your lost messages sent right after joining a group? There is a known issue about occasional message lose in such case https://github.com/Azure/azure-signalr/issues/87. It will be fix with the upcoming SDK.

Meanwhile, could you send your instance name to `lianwei@microsoft.com`, for me to further check if there was any service error happening at that time?

**Comment by ericbrunner** [comment] 2018-08-14 06:07
Hi @vicancy 

 l asume that I loose messages from my Hub on the way to the Azure SignalR Service. I have already enabled `EnableDetailedErrors = true`.
I don't use groups. From my WebApp client I currently only invoked a Join method in the Hub and then form my Azure Function I trigger the SendDirectMessage (e.g. via browser for test purposes). And here I see that the Azure Function with the SignalR .NET client runs properly without exception and invoked the SendDirectMessage method in my Hub with is in another Api App in Azure. The Hub properly sends the message to the Azure SignalR Service and then there is no trace anymore from the lost message.

Here is my [Azure Function Code](https://gist.github.com/cnlogistics/f631c20d8feb4daa0f1f69edc8a17644) and [csproj](https://gist.github.com/ericbrunner/3276e21a6400ff69f6a5c7aae435775b)
Here is my [Hub Code](https://gist.github.com/ericbrunner/1b1b75d8593dca416ccfa6a975e26d9f) and [Startup Code](https://gist.github.com/ericbrunner/74083214244b47efb5c0dc97e930f227) and [csproj](https://gist.github.com/ericbrunner/4d0325d2a44cf38b226874491a679abd)

What I use is the TruckerWebAppHub (route: `/truckerwebapp`) from my Azure Function. Only for clarification. The other Hub was only an initial starting point and is **not used** in t**hat scenario**.
But for completion here is the [Code of the other Hub](https://gist.github.com/ericbrunner/b7286420f7443d5719bd18e6efd538b2) (route: `/roltruckcomm`).

I send you an email of all I can provide about the used SignalR Hub.

**Comment by vicancy** [comment] 2018-08-14 08:13
Hi @ericbrunner 
Based on your description, I draw a diagram of your current workflow, is it correct?
![image](https://user-images.githubusercontent.com/668244/44078806-031c2e44-9fda-11e8-9d30-324cad8e6343.png)

> The Hub properly sends the message to the Azure SignalR Service and then there is no trace anymore from the lost message

Does it mean that you see "SignalR-Message-Sent" event logged from the *Azure WebApp* side?

> Occasionally don't arrive

Does it mean that sometimes *WebApp Client* does receive the message?

Could you also turn on client side logging following https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-logging so that we can first make sure that the *client<->Azure SignalR Service* connection works properly ( If the connection is lost, then the message is as a result lost)?

After looking at the service logging, I am not able to find any suspicious logs possibly causing the issue. It would be appreciated if you could repro the issue, and provide us:
1. The approximate time range when the issue happens
2. The client `connectionId` (the client who fails to receive the message)

**Comment by ericbrunner** [comment] 2018-08-14 11:02
@vicancy 

Here a first intermediate result of exception:

Azure Web App (hosting the Hub)

![image](https://user-images.githubusercontent.com/6480047/44087944-b1c2f3b0-9fc1-11e8-97ad-b154cd3980e6.png)

Application Insights export of those server side exceptions
[TruckerWebAppHubApiApp_query_data.xlsx](https://github.com/Azure/azure-signalr/files/2286617/TruckerWebAppHubApiApp_query_data.xlsx)

Azure Function (invokes the SendDirectMessage)
Here I already opened another [issue](https://github.com/aspnet/SignalR/issues/2791) because its a Asp.Net Core .NET Client  problem that several times the StartAsync() throws an exception. I built defensive code to mitigate that.

![image](https://user-images.githubusercontent.com/6480047/44088097-300baf50-9fc2-11e8-9c8b-fc70b7c950d7.png)

**Comment by ericbrunner** [comment] 2018-08-14 12:15
Hi again @vicancy 
Until yesterday my App Service Plan ran only on 1 instance. I configured an auto-scaler to increase to 2 instances (VMs) when CPU load raises above 70%. Yesterday midday the autoscaler increased the instances from 1 to 2. The Azure Function App had ARR disabled. So it can be that that was the root cause. So maybe the initial connect request was on the 1st instance (VM#1) and after autoscaler took place the other or some requests where transferred to 2nd instance (VM#2). 
Thats only a guess but makes sense.

Yesterday at 8 p.m. I disabled auto-scaler for first and enabled on all my related apps ARR.
Thanks to @anurse . He mentioned that in another issue....

**Comment by ericbrunner** [comment] 2018-08-14 13:05
Hi @vicancy 
Currently I had that case that I didn't get the SignalR messages in my deployed (in azure) **Web App Client**.

Steps for Reproduction

1. I startet the **Azure Function** project on `localhost`
2. I startet the **Api App** project (with SignalR hub) on `localhost`
    That **Api App** on `localhost` is connected to the **same Azure SignalR Service** as my deployed **Api App** in azure. So they share it in a kind of way.

3. I started the **Web App Client** on `localhost`
4. I launched the in Azure deployed **WebApp Client**
5. I triggered the in Azure deployed **Azure Function** 
6. The SignalR message was delivered to my `localhost` started **Web App Client** but not to the in Azure deployed **Web App Client**

Well that raised question marks .....

When I stopped the **Api App** (where the Hub resides) project on `localhost` and repeated step 5 I finally got the SignalR message in my in Azure deployed **Web App Client**.

Do I have to create a separate Azure SignalR Service for localhost development or what would you suggest?

I attached that Application Insight logs from that timespan which shows several exceptions:
[TruckerWebAppHub_Exceptions.xlsx](https://github.com/Azure/azure-signalr/files/2286943/TruckerWebAppHub_Exceptions.xlsx)

and the Api App Diagnostic Logs that I persist in Azure Storage:
[TruckerWebAppHub_Logs.zip](https://github.com/Azure/azure-signalr/files/2286959/TruckerWebAppHub_Logs.zip)

**Comment by vicancy** [comment] 2018-08-15 03:41
Hi @ericbrunner 
Thanks for your investigation, your explanation about "those users are not there and the request goes in empty space" makes pretty much sense to me that it caused the original issue. 

Any concerns preventing you from using `Clients.User(userid).SendAsync()`?

For your latest problem, I assume it is the same case as the "auto-scaling" case before that there are 2 App instance running, one is the Azure one and one is the `localhost` one, so if you are still using [TruckerWebAppHub](https://gist.github.com/ericbrunner/1b1b75d8593dca416ccfa6a975e26d9f), it still encountered the same problem.

**Comment by cnlogistics** [comment] 2018-08-15 03:57
Hi 
Regarding

Any concerns preventing you from using Clients.User(userid).SendAsync()?

I use that in my hub. What do you mean?

Regarding localhost development:
Well I don't agree on that. Because when I stop the localhost debug session the messages appear in my deployed Web App Client. Anyway, what would you suggest?
From my point of view 1 have 2 options
Oprion1: Create a 2nd Azure SignalR Service resource that I only use for localhost debugging
Option2: I only use AddSignalR() without AddAzurreSignalR() in localhost debugging

**Comment by cnlogistics** [comment] 2018-08-15 04:10
For me it seems that only one same Hub can be connected to Azure SignalR Service and that First Come First Serve Policy takes place in Azure SignalR Service. So any message deliveries are only sent to that Hub that registered first in the endpoint. If the first hub disconnects (my localhost hub) the other one (remote hub in azure) is used

**Comment by vicancy** [comment] 2018-08-15 04:38
Hi @cnlogistics , 
> I use that in my hub. What do you mean?
I mean why not sending to user directly using `Clients.User` instead of `Clients.Client` in https://gist.github.com/ericbrunner/1b1b75d8593dca416ccfa6a975e26d9f#file-truckerwebapphub-cs-L106

> only one same Hub can be connected to Azure SignalR Service
No it's not. Azure SignalR Service supports multiple App Servers( in your case, an Azure one, and a localhost one), and it uses Redis Service for routing and scaling. You can try a "broadcast" case using `Clients.All.SendAsync` to see if both clients can get messages, with both App Servers on.

**Comment by ericbrunner** [comment] 2018-08-15 06:39
Hi @vicancy 

> I mean why not sending to user directly using Clients.User instead of Clients.Client in https://gist.github.com/ericbrunner/1b1b75d8593dca416ccfa6a975e26d9f#file-truckerwebapphub-cs-L106

What's the difference between `Clients.User` and `Clients.Client` in **my case**.

To be honest, it's hard to describe in text what is going on. I will try to record a screencast and post it here. Another option would be to establish a Remote Session with you (e.g. LogMe).

**Comment by vicancy** [comment] 2018-08-15 07:32
Hi @ericbrunner , a screencast can be helpful. Have you tried `Clients.All.SendAsync`? Is that working?

> What's the difference between Clients.User and Clients.Client in my case.

With `Clients.User`, Azure SignalR service will find all the connections related to the user (the info is maintained globally in Azure Redis so it is shared across App Servers, in your current case, the info in memory is per App Server only) for you.

So here is my understanding to what happens to your case:

> 1. I started the Azure Function project on localhost

So, in the moment, the *Azure WebApp with Hub* is running, and *Azure SignalR Service* is running, am I understanding correctly?

> 2. I startet the Api App project (with SignalR hub) on `localhost`

Now, another *WebApp with Hub* on `localhost` runs, and it connects to *Azure SignalR Service*.

> 3. That Api App on `localhost` is connected to the same Azure SignalR Service as my deployed Api App in azure. So they share it in a kind of way.

Yes, correct, it is similar to *2 API App in Azure* of your auto-scale case.

> 4. I started the Web App Client on `localhost`

The client tries to connect, and *Azure SignalR Service* randomly picks one server, we assume this is the *localhost* one. So the Hub running in *localhost* now knows this client and stores the info into the in-memory `HubUsers`

> 5. I launched the in Azure deployed WebApp Client

The client tries to connect, and *Azure SignalR Service* randomly picks one server, we assume this is the *Azure WebApp* one. So the Hub running in *Azure* now knows this client and stores the info into the in-memory `HubUsers`

> 6. I triggered the in Azure deployed Azure Function

The Azure Function tries to connect, and *Azure SignalR Service* randomly picks one server, in this case, the *localhost* one. However, as step4 indicates, the *localhost WebApp* only has knowledge of the *localhost* client.

> 7. The SignalR message was delivered to my localhost started Web App Client but not to the in Azure deployed Web App Client

So because the *localhost WebApp* only has knowledge of the *localhost* client, only the *localhost* client receives the message.

When you stop your *localhost WebApp*, the *localhost* client reconnects to the *Azure WebApp*, and now *Azure WebApp* knows 2 clients. Azure function calls, and message goes to *Azure WebApp*, so 2 clients receive message.

To verify if my understanding is correct, you can
1. Log how many connections are fetched and Send in your Hub
2. Use `Clients.All.SendAsync`, to see if all the clients now receive messages.

Please feel free to let me know if I misunderstand anything.

**Comment by ericbrunner** [comment] 2018-08-15 07:58
Hi @vicancy 

1. Thank you for your support. I really appreciate it 👍 
2. My way with the `ASPNETCORE_ENVIRONMENT=DevelopmentLocalhost` (see last [comment ](https://github.com/Azure/azure-signalr/issues/160#issuecomment-413115602)from me) works as expected 👍 
3. The key statement in your last comment is: 

> " ... Azure SignalR Service randomly picks one server ..."

That's was what I ment with **First Come First Serve**.

4. Me [screencast ](https://screencast-o-matic.com/watch/cFjoiQqIoz)from my last comment shows that all.

5. I will try that `Clients.User`. Did'nt know our read anything about that that only `Clients.User` finds all the connections and `Clients.Client` does not.

From my point of view you can close that issue

**Comment by vicancy** [comment] 2018-08-15 08:27
@ericbrunner Thanks for your patience, I will close the issue.
Clarify some gaps though:
1. Azure SignalR Service randomly picks one server only when client tries to connect, for traffic load balance purpose, once it is connected, Azure SignalR Service will guarantee that the client traffic *always* goes into the that particular App Server.
2. It is not "Clients.User finds all the connections and Clients.Client does not", but that when using `Clients.Client` you have to maintain the *connection<->user* mapping in your own Hub code correctly, as you mentioned before, through **a central database table or azure storage**. With that implemented, I believe your `localhost` machine can also connect to Azure SignalR Service using `Client.Client`. 😄

**Closed by vicancy** 2018-08-15 08:27 UTC
Labels: question

**Comment by anurse** [comment] 2018-08-15 15:51
Regarding `Clients.User`, see our documentation on [Users and Groups](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1) for more information. Once you've enabled authentication as described in our [Authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1) docs, you can send to all connections associated with a user using `Clients.User`.
