### ISSUE TITLE
SignalR Azure does not seem to use provided id from custom IUserIdProvider

### ISSUE THREAD

**Issue by Hypnobrew** [Azure/azure-signalr#140] opened 2018-07-09 19:02 UTC
Hi

I first opened an [issue](https://github.com/aspnet/SignalR/issues/2602) in [aspnet/signalr](https://github.com/aspnet/SignalR) repository, but the problem seem to be related to the library `Microsoft.Azure.SignalR` on top of SignalR.

Experienced issue:
Using a custom user id provider implementing `IUserIdProvider` does not seem to work. I can see it hitting my breakpoint, but does not use my custom user id.

Without using the Azure Signal R service, it work as expected. But with Azure service it does not seem to have any effect what I return other than the JWT claim `NameIdentifier` used as default.

How to recreate:
1. Create a new web project `dotnet new mvc`
2. Add the package `Microsoft.Azure.SignalR`
3. Add the client library from npm
4. Implement a custom user id provider (`IUserIdProvider`) and register it in `Startup.cs`
5. Return some custom id from the class above.
6. Try to send a message from the client using the custom id specified.

- .Net Core 2.1.1
- Microsoft.Azure.SignalR 1.0.0-preview1-10015
- @aspnet/signalr 1.0.0
- Javascript client from Latest Chrome
- Kestrel
- Ubuntu 18.04 (Tried on Windows 10 as well)

**Comment by cristoffer-andersson-stratsys** [comment] 2018-07-12 06:14
My user id is created something like this in my `IUserIdProvider` implementation:
```
var nameIdentifier = connection.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value
var issuer = connection.User?.FindFirst(ClaimTypes.Issuer)?.Value
return nameIdentifier + issuer;
```

**Comment by cristoffer-andersson-stratsys** [comment] 2018-07-12 06:16
Also tried with a dummy value `ABC123` in my implementation, and still only matches with the `NameIdentifier` claim on my User.

**Comment by Hypnobrew** [comment] 2018-07-12 07:05
My user id is created something like this in my IUserIdProvider implementation:

```
var nameIdentifier = connection.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value
var issuer = connection.User?.FindFirst(ClaimTypes.Issuer)?.Value
return nameIdentifier + issuer;
```
Also tried with a dummy value ABC123 in my implementation, and still only matches with the NameIdentifier claim on my User.

**Comment by xscript** [comment] 2018-07-12 07:09
Ah, I think I get your question.
Yeah, this is the expected behavior for now, because we use `NameIdentifier` in the service runtime to identify each connection. This is a gap right now to honor custom `IUserIdProvider` in service runtime. Let me think a bit to find out a fix for this.

**Comment by davidfowl** [comment] 2018-07-12 07:10
Right i was going to suggest sticking the resolved id in a claim on the sdk side that flows to the service.

**Comment by Hypnobrew** [comment] 2018-07-12 13:20
Great, thanks!

**Comment by xscript** [comment] 2018-09-28 04:50
The latest SDK (version 1.0.0) has supported custom `IUserIdProvider`.
Close this issue.

**Closed by xscript** 2018-09-28 04:50 UTC
Labels: bug
