### ISSUE TITLE
Custom `exp` claim will be overridden by Service SDK

### ISSUE THREAD

**Issue by xscript** [Azure/azure-signalr#112] opened 2018-05-29 09:10 UTC
The access token generated by SDK will have below claims by default:
- `aud`
- `exp`
- `iat`
- `nbf`

When users have their own claims, there might be conflicts.

- Multiple `aud` claims will become an array, so there is no conflict.
- Custom `exp` will be overridden by Service SDK. The default expiration time is [one hour](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/ServiceOptions.cs#L22). User can customize it with [AccessTokenLifetime option](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/ServiceOptions.cs#L44).
- `iat` will be overridden. No work around. Service SDK should not generate it.
- `nbf` will be overridden. No work around. Service SDK should not generate it.

**Comment by davidfowl** [comment] 2018-09-29 08:03
This should just be documented and then we can close the issue.

**Comment by vicancy** [comment] 2019-04-28 03:35
The issue is fixed by providing a user claim prefix to preserve the user claims and convert it back when regenerating the claims for http requests. https://github.com/Azure/azure-signalr/pull/465/files

**Closed by vicancy** 2019-04-28 03:35 UTC
Labels: enhancement
