### ISSUE TITLE
No error thrown from AddAsync when ConnectionStringSetting is not provided for the C# function binding

### ISSUE THREAD

**Issue by alteredtastes** [Azure/azure-signalr#1558] opened 2022-02-16 22:58 UTC
### Describe the bug

For a while, I was blocked trying to understand why SignalR service was not sending messages to my group, when negotiate and adding to the group were appearing to work fine. 

Using examples from the docs ([here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-output?tabs=csharp)), I found that the `ConnectionStringSetting = <Signal R Connection String>` parameter is not provided for the C# examples. This took a while to figure out, and I have submitted a separate docs issue on that page ([here](https://github.com/MicrosoftDocs/azure-docs/issues/88219)).

While I was debugging the issue, I had attempted to use try/catch to wrap `await signalRMessages.AddAsync(...)` and figure out where things were going wrong, but no exception was ever thrown.  The AddAsync method is missing some essential error handling and, in my humble opinion, its absence should constitute a bug. Nothing indicated that no connection string was provided for the SignalR binding, I was just lucky that I found an example elsewhere that had it included.

### To Reproduce

Use the Send To a Group example from the docs and see that it will fail to send any messages. Wrap the signalRMessages.AddAsync(...) method call in a try/catch and see that no error is thrown.

We will close this issue if:
- the repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
- if we will not be able to repro the behavior you're reporting
-->

### Further technical details
- Azure Signal R serverless mode
- Microsoft.AspNetCore.SignalR 1.1.0
- "@microsoft/signalr": "^5.0.10",

**Comment by Y-Sindo** [comment] 2022-02-17 07:05
The `ConnectionStringSetting` is not necessary. It has a default value of `AzureSignalRConnectionString`. You could check [this](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/samples/simple-chat/csharp/FunctionApp/Functions.cs#L28) for a full sample. You might want to enable full logs to see what happened in your functions by adding the `logging` property in the top level of `host.json`:
```
{
  "logging": {
    "logLevel": {
      "default": "Debug"
    }
  }
}
```

**Comment by alteredtastes** [comment] 2022-02-17 07:44
I was doing this locally and in local.settings.json I did have...
```
{
   ...
   "Values": {
      "AzureSignalRConnectionString": <Signal R Connection String>
   }
   ...
}
```

Negotiate and adding to group worked, so perhaps they read the "AzureSignalRConnectionString" naming convention fine by default. Sending to the group afterwards however would not work without explicitly passing "ConnectionStringSetting" pointing to the string in local settings Values.

I've not rechecked with new log settings you suggested, but I thought I'd still reply with the info above ☝️

**Comment by Y-Sindo** [comment] 2022-02-17 08:40
I can't reproduce the problem. What's the SignalR extension version?

**Comment by alteredtastes** [comment] 2022-02-17 18:17
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.6.0" />

**Comment by Y-Sindo** [comment] 2022-02-18 06:50
Version 1.6.0 works well in my tests. Could you provide a minimum project to reproduce the problem?

**Comment by alteredtastes** [comment] 2022-02-23 19:32
Sorry I've had quite a lot going on, will try to repro in a separate project soon.

**Comment by alteredtastes** [comment] 2022-02-23 19:36
I will say however.. I find passing ConnectionStringSetting to be preferable. It is harder to know how the connection string is being referenced for SignalR when it is done implicitly via the default check and naming convention of "AzureSignalRConnectionString".

**Comment by Y-Sindo** [comment] 2022-02-24 03:50
The `ConnectionStringSetting` itself has a default value `AzureSignalRConnectionString`, and all SignalR output bindings with the same connection string setting share a same SignalR hub context, so there should be no differences. I'll close this issue as it is unreproducible. Feel free to reopen it if you have new evidence.

**Closed by Y-Sindo** 2022-02-24 03:50 UTC
