### ISSUE TITLE
Connection to Azure service drops and cannot automatically recover

### ISSUE THREAD

**Issue by johnrutherford** [Azure/azure-signalr#402] opened 2019-02-21 19:41 UTC
Yesterday our web applications had connections to the Azure SignalR service dropped. We got several errors like this:

```
Connection "0a2f27dc-80e1-451e-aa4d-999d4bb950c6" to the service was dropped.

System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at async Task<WebSocketReceiveResult> System.Net.WebSockets.WebSocketBase+WebSocketOperation.Process(Nullable<ArraySegment<byte>> buffer, CancellationToken cancellationToken)
   at async Task<WebSocketReceiveResult> System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(ArraySegment<byte> buffer, CancellationToken cancellationToken)
   at async Task Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at void System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at void System.IO.Pipelines.Pipe.GetReadResult(ref ReadResult result)
   at ReadResult System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at async Task Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()
```

It looked like one application instance dropped all connections and the other only dropped one.

Then we got several thousand of these errors:

```
Error while sending message to the service.

Microsoft.Azure.SignalR.Common.ServiceConnectionNotActiveException: The connection is not active, data cannot be sent to the service.
   at async Task Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at async Task Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
```

Then several thousand of these:

```
Failed writing message. Aborting connection.

System.InvalidOperationException: Writing is not allowed after writer was completed.
   at void System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at Memory<byte> System.IO.Pipelines.Pipe.GetMemory(int sizeHint)
   at Span<byte> System.IO.Pipelines.Pipe+DefaultPipeWriter.GetSpan(int sizeHint)
   at ValueTask<FlushResult> System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory<byte> source, CancellationToken cancellationToken)
   at async Task Microsoft.AspNetCore.SignalR.HubConnectionContext.TryWritePingSlowAsync()
```

This went on for over an hour until the web applications were manually restarted. Then the apps were able to re-connect and things were fine. 

Versions:
JS client: 1.1.0
Microsoft.AspNetCore.SignalR: 1.1.0
Microsoft.Azure.SignalR: 1.0.6

**Comment by vwxyzh** [comment] 2019-02-22 06:16
Are there many logs like `Failed to connect to the service`?

**Comment by johnrutherford** [comment] 2019-02-22 14:12
@vwxyzh I did find a few more error messages buried in the logs. There were 8 of each of these. So it looks like it tried to re-connect and then gave up.

```
Failed to start connection. Error starting transport 'WebSockets'.

System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at WebResponse System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   at async Task System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at async Task System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at async Task Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat)
   at async Task Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat)
```

```
Failed to connect to the service: "Unable to connect to the remote server The remote server returned an error: (502) Bad Gateway.".

System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at WebResponse System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   at async Task System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at async Task System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at async Task Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat)
   at async Task Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat)
   at async Task Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat)
   at async Task Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat)
   at async Task Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at async Task<ConnectionContext> Microsoft.Azure.SignalR.ConnectionFactory.ConnectAsync(TransferFormat transferFormat, string connectionId, string target, CancellationToken cancellationToken)
   at async Task<ConnectionContext> Microsoft.Azure.SignalR.ConnectionFactory.ConnectAsync(TransferFormat transferFormat, string connectionId, string target, CancellationToken cancellationToken)
   at async Task<bool> Microsoft.Azure.SignalR.ServiceConnectionBase.StartAsyncCore(string target)
```

**Comment by OlympicLarry** [comment] 2019-02-23 22:08
This has been happening to me daily and I had to switch back to local signalR today.

**Comment by fabiano** [comment] 2019-02-26 00:17
We are having the same errors here. Checking the Metrics page, we saw that at the same time of the errors the number of connections drops.

![connections](https://user-images.githubusercontent.com/2686/53377832-2f8e7200-3942-11e9-948c-1bb74ec70f49.png)

These are some of the error messages:

```
15:52:46.808 [53] ERR Microsoft.Azure.SignalR.ServiceConnectionBase -> Connection e34eab1c-34bf-46fb-bc07-31d2843fa0fb to the service was dropped.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()
```

```
15:53:13.358 [73] ERR Microsoft.Azure.SignalR.ServiceConnection -> Error while sending message to the service.
Microsoft.Azure.SignalR.Common.ServiceConnectionNotActiveException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
```

```
15:53:15.870 [197] ERR Microsoft.Azure.SignalR.ServiceConnectionBase -> Service timeout. 30000.00ms elapsed without receiving a message from service.
```

```
15:53:31.865 [182] ERR Microsoft.Azure.SignalR.ServiceConnectionBase -> Error receiving handshake response.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnectionBase.<ReceiveHandshakeResponseAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SignalR.ServiceConnectionBase.<HandshakeAsync>d__56.MoveNext()
```

Versions:

- JavaScript client: 1.1.2
- Microsoft.AspNetCore.SignalR: 1.1.0
- Microsoft.Azure.SignalR: 1.0.6

**Comment by vwxyzh** [comment] 2019-02-26 09:17
@johnrutherford 

* Following exceptions are logging server connection dropped.
```
Connection "0a2f27dc-80e1-451e-aa4d-999d4bb950c6" to the service was dropped.

System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at async Task<WebSocketReceiveResult> System.Net.WebSockets.WebSocketBase+WebSocketOperation.Process(Nullable<ArraySegment<byte>> buffer, CancellationToken cancellationToken)
   at async Task<WebSocketReceiveResult> System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(ArraySegment<byte> buffer, CancellationToken cancellationToken)
   at async Task Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at void System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at void System.IO.Pipelines.Pipe.GetReadResult(ref ReadResult result)
   at ReadResult System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at async Task Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()
```

* Following exceptions are logging client connection dropped, so if you have several thousand clients on the dropped server connections, several thousand is a reasonable count.
```
Error while sending message to the service.

Microsoft.Azure.SignalR.Common.ServiceConnectionNotActiveException: The connection is not active, data cannot be sent to the service.
   at async Task Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at async Task Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
```

* Following exception is a bug, we didn't remove the clients on dropped server connections, it will throw forever, we have a PR to fix this bug. You can still use your hub server, these exceptions are noise.
```
Failed writing message. Aborting connection.

System.InvalidOperationException: Writing is not allowed after writer was completed.
   at void System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at Memory<byte> System.IO.Pipelines.Pipe.GetMemory(int sizeHint)
   at Span<byte> System.IO.Pipelines.Pipe+DefaultPipeWriter.GetSpan(int sizeHint)
   at ValueTask<FlushResult> System.IO.Pipelines.PipeWriter.WriteAsync(ReadOnlyMemory<byte> source, CancellationToken cancellationToken)
   at async Task Microsoft.AspNetCore.SignalR.HubConnectionContext.TryWritePingSlowAsync()
```

**Comment by johnrutherford** [comment] 2019-02-28 14:17
@vwxyzh thank you for the explanation. That makes sense. 

When can we expect a new version to fix the bug with not removing the dropped connections?

And what about the 502 error when our application tried to reconnect to the service?

**Comment by vwxyzh** [comment] 2019-03-04 05:40
@fabiano yours is a different case. We will trace it in your issue.

**Comment by vwxyzh** [comment] 2019-03-04 05:44
@johnrutherford we are testing the new version, we will at you when we published.

**Comment by vicancy** [comment] 2019-03-22 05:55
1.0.7 solves the `Failed writing message. Aborting connection.` issue.

**Comment by johnrutherford** [comment] 2019-03-22 13:12
@vicancy, thanks. We'll try it out.

**Comment by vicancy** [comment] 2019-03-25 10:00
Correction: 1.0.8 includes the fix, we are releasing 1.0.8 in 2 days.

**Comment by yosigolan** [comment] 2019-03-26 12:23
Hey.
i am seeing the same issue. 
upgraded to 1.0.8 and it didn't solved the issue. this bug started to happen in my environment on 23.3.19.
since than it happens every few hours and in order to solve it i need to restart the azure signal r service.
these are the errors i get in the log (on local env and production server):
`
WebSocket closed by the server. Close status NormalClosure.
Connection "a1037afb-77fe-47b2-ab14-e5ddab0cde1d" received error message from service: "PingTimeout"
Transport is stopping.
HttpConnection Disposed.
Error while sending message to the service.
Service timeout. 30000.00ms elapsed without receiving a message from service.
Starting transport. Transfer mode: Binary. Url: 'wss://signalr-service-seevoov.service.signalr.net/server/?hub=hubtripplan&cid=1ccbd9d2-8810-42a1-b080-196daf88e82e'.
Error while sending message to the service.
Client negotiate failed: "Azure SignalR Service is not connected yet, please try again later."
Client negotiate failed: "Azure SignalR Service is not connected yet, please try again later."
...
`


Yosi

**Comment by vicancy** [comment] 2019-03-27 06:30
Hi @yosigolan Any other logs? "PingTimeout" can happen sometime when the Azure Service is reloading or switching to other running pods. Could you send me through email your app server side log when the issue took place and during the period that the connection was not able to reconnect?

**Comment by yosigolan** [comment] 2019-03-27 09:06
@vicancy it happen again this night. this is how it looks from your side:
![image](https://user-images.githubusercontent.com/18391088/55063058-df5d1980-507f-11e9-8ae0-bab9468cdbd3.png)

and this are the errors from my side:

[gae_app_module_id_apps-web-service_version_id_20190326t154926__logs__2019-03-27T09-43.txt](https://github.com/Azure/azure-signalr/files/3012342/gae_app_module_id_apps-web-service_version_id_20190326t154926__logs__2019-03-27T09-43.txt)

**Comment by yosigolan** [comment] 2019-03-31 11:40
The issue happen to me again today. this time i noticed it happen when the server connection number increased. there are situations in my system that the services move from one server to another. in these situations, for a short time the connection number is doubled since during the transition the service runs on both of the servers. once the server connection was increased the connection drop. it reaches 20 connections. is there a a limit on the server connection number?

**Comment by sladewasinger** [comment] 2019-04-01 02:39
I'm having similar issues. I've had to make a signalr service 3 times now because they eventually fail and my web server can't connect to them. I receive similar errors as the OP.

@yosigolan, 20 connections is the max for the free tier.

**Comment by vicancy** [comment] 2019-04-01 03:08
We are actively investigating the issue that **under some conditions the server connection drops and not able to automatically reconnect back until user manually restart the Azure Service.** 

@sladewasinger Are you seeing the same issue?

**Comment by vicancy** [comment] 2019-04-01 04:59
Hi @yosigolan For the server connection count showing 0 in portal starting from 2019-03-27T02:34:53 UTC, that is caused by a bug introduced in when upgrading our metrics reporting system that the metrics data was not successfully sent to the portal. After you restarted the service, the issue was mitigated. I checked your instance, during that period from 2019-03-27T02:34:53+00:00 to 2019-03-27T03:28:00+00:00 actually there were 10 server connections connected to the service.

**Comment by vicancy** [comment] 2019-04-01 05:01
Hi @sladewasinger , as explained above, there was an issue in metrics display in the Azure portal, restart the Azure Service can solve the display problem. But according to your description, your issue is not resolved after 3 times restart? Could you share with me more details about your issue? You can email me the time range when error occurred, your instance name and the detailed error you saw for me to have a check.

**Comment by yosigolan** [comment] 2019-04-01 07:04
@vicancy Thanks.
still my servers ware not able to connect.
regarding the max 10 server connections on the free tier, i had cases where i saw in the metrics 25 and 30 servers connected. how is that so? also, when the connection is bane due to max connection limit, what is the error code?
i think it should be documented, currently the documentation only mention the clients connections limitis.

Thanks

**Comment by vicancy** [comment] 2019-04-01 07:11
@yosigolan Connection limits are client+server connections in total, that is 20.

**Comment by yosigolan** [comment] 2019-04-01 07:15
@vicancy thanks for the clarifying. i think it should be stated in the pricing doc as i didn't understand it that way.
is there a way to configure the server connections number (default is 5)?

Thanks Yosi

**Comment by sladewasinger** [comment] 2019-04-01 21:24
@vicancy The signalr service randomly shuts down and sends an error to all connected clients. You can see in the image below, right around 1500 hours is where the message count dropped to 0. Usually the service will eventually recover and the clients can reconnect.

The javascript clients get this error: **signalr.js:1881 Error: Connection disconnected with error 'Error: Server returned an error on close: ServerOffline'.** 

I got a bunch of these errors on the server on March 30th around 1500 hours:
**Azure SignalR Service is not connected yet, please try again later.
Microsoft.Azure.SignalR.Common.AzureSignalRNotConnectedException:
   at Microsoft.Azure.SignalR.DefaultEndpointRouter.GetNegotiateEndpoints (Microsoft.Azure.SignalR.Common, Version=1.0.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)**. . .


![image](https://user-images.githubusercontent.com/16869873/55359882-2b4cfb80-5490-11e9-87ae-1420076f7dba.png)

If you need more information from me, just let me know! I'll email you the instance name

**Comment by vicancy** [comment] 2019-04-02 02:06
@yosigolan yeah, please refer to https://github.com/Azure/azure-signalr/blob/dev/docs/use-signalr-service.md#connectioncount

**Comment by yosigolan** [comment] 2019-04-02 06:46
@vicancy Thank you.

**Comment by NArnott** [comment] 2019-05-17 14:59
This seems to be happening twice a week for us, forcing us to restart our service that connected to Azure SignalR.

```
Microsoft.Azure.SignalR.Common.ServiceConnectionNotActiveException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
```

We're currently using Microsoft.Azure.SignalR version 1.0.9. This is on a Standard Tier, 1 unit Azure SignalR instance.

This is our startup code:

```
public void ConfigureServices(IServiceCollection services)
{
...

            var signalRBuilder = services.AddSignalR();
            if (!Env.IsDevelopment())
            {
                signalRBuilder.AddAzureSignalR(x =>
                {
                    x.ConnectionString = Configuration.GetConnectionString("AzureSignalR");

                    //Seperate out each environment into a seperate SignalR service
                    x.ApplicationName = Env.EnvironmentName;

                    if (!Env.IsProduction())
                    {
                        //We don't need the default 5 connections for test environments.
                        x.ConnectionCount = 1;
                    }
                });
            }
...
}

public void Configure(IApplicationBuilder app)
{
...
            if (Env.IsDevelopment())
            {
                app.UseSignalR(x =>
                {
                    x.MapHub<PushNotificationsHub>("/hubs/pushNotifications");
                });
            }
            else
            {
                app.UseAzureSignalR(x =>
                {
                    x.MapHub<PushNotificationsHub>("/hubs/pushNotifications");
                });
            }
...
}

```

**Comment by pablo-meyer** [comment] 2019-07-29 21:25
@NArnott Any advances on this? we are experiencing a similar issue

**Comment by vicancy** [comment] 2019-07-30 04:01
Hi  @NArnott @pablo-meyer

As stated in https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#server-connection-drop
> As the connections between app server and SignalR Service are persistent connections, they may experience network connectivity issues. In the Server SDK, we have Always Reconnect strategy to server connections. As the best practice, we also encourage users to add continuous reconnect logic to the clients with a random delay time to avoid massive simultaneous requests to the server.

> On regular basis there are new version releases for the Azure SignalR Service, and sometimes the Azure wide OS patching or upgrades or occasionally interruption from our dependent services. These may bring in a very short period of service disruption, but as long as client side has the disconnect/reconnect mechanism, the impact is minimal like any client-side caused disconnect-reconnect.

Too frequent connection drops are not expected, you can email me your instance name and the timestamp of the drop for me to check the root cause if you think the drops are abnormal.

**Comment by pablo-meyer** [comment] 2019-08-02 12:18
Thanks @vicancy, Ill give you the info the next time this happens...

**Comment by yosigolan** [comment] 2019-08-04 10:52
Hey. i also experienced these problems few month ago when the issue was opened and it fixed. on the 26.7 it happen to me again for few hours. on the dashboard i saw are about 17 connections which prevented new client connections. restart dident solved it. eventually, it fixed by itself. i then saw it again the day after and now everything works as should.

**Comment by vicancy** [comment] 2019-08-05 02:55
@yosigolan sounds like you are hitting the 20 limit quota so that when every day starts the issue recovers? 
Here has a detailed TSG on how to view client-side network traffic https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#tips

**Comment by vicancy** [comment] 2019-08-05 02:57
I am going to close this issue as the original one should be addressed.

Please open new issue providing detailed error responses from client and server when possible following https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#tips if you encounter similar issues.

Thanks

**Closed by vicancy** 2019-08-05 02:57 UTC
Labels: bug
