### ISSUE TITLE
Cannot send dependency to Configure that depends on IHubContext

### ISSUE THREAD

**Issue by gavilanch** [Azure/azure-signalr#194] opened 2018-09-11 00:08 UTC
An error is thrown when passing a custom service to the Configure method of the Startup class when using AddAzureSignalR service. This is in ASP.NET Core 2.1. My code:

```
public interface IDatabaseChangeNotificationService
    {
        void Config();
    }
```

```
public class SqlDependencyService : IDatabaseChangeNotificationService
{
public SqlDependencyService( IHubContext<ChatHub> chatHub)
        {
        }

        public void Config()
        {
        }
}

// in the ConfigureServices method:

services.AddScoped<IDatabaseChangeNotificationService, SqlDependencyService>();

            services.AddSignalR().AddAzureSignalR("My Secret key");

// Configure method:

public void Configure(IApplicationBuilder app,
            IHostingEnvironment env,
            IDatabaseChangeNotificationService notificationService)
 {
if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseAzureSignalR(x =>
            {
                x.MapHub<ChatHub>("/chatHub");
            });

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            notificationService.Config();
}

```
Where ChatHub is a class the inherits from Hub (no constructor on this class). If I run the app, I get the following error:

> System.InvalidOperationException: 'AddAzureSignalR(...)' was called without a matching call to 'IApplicationBuilder.UseAzureSignalR(...)'.
>    at Microsoft.Azure.SignalR.ServiceLifetimeManager`1..ctor(IServiceConnectionManager`1 serviceConnectionManager, IClientConnectionManager clientConnectionManager, IHubProtocolResolver protocolResolver, ILogger`1 logger, AzureSignalRMarkerService marker)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
> 

The issue goes away if I remove the IHubContext dependency from the SqlDependencyService class, or if I remove the use of the functions AddAzureSignalR and UseAzureSignalR.

**Comment by xscript** [comment] 2018-09-11 06:26
We will check whether `UseAzureSignalR` is called in methods of `HubLifetimeManager` instead of constructor.

**Comment by davidfowl** [comment] 2018-09-11 08:10
@xscript That would be much cleaner. We do a similar thing in redis (https://github.com/aspnet/SignalR/blob/adc5706bcb2b3cb85e98e303999eb9a778426f7c/src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs#L490)

**Comment by Jaternius** [comment] 2018-10-09 10:27
We've been struck by this issue as well. We need to perform some calls as part of the startup of our service after the IoC container was set up, but before the webhost has been started (by building the webhost, creating service scope, and resolving the required services from it). Somewhere down the line, a singleton is required which in turn requires an `IHubContext<>`. This is merely injected though and no operation is performed with it during the startup process.

The singleton cannot be instantiated however because of this exception. We've worked around it by creating a new class implementing the same interface as the singleton, registering the singleton as its own type (instead of its interface), and have the wrapper class use a `Lazy<Singleton>` instead. It works, but we would really like to see this exception gone.

**Comment by curtisconner** [comment] 2019-06-26 04:55
OK guys I am also stuck with the same issue

Here is my configure code
public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<Dx1Configuration>(Configuration.GetSection("Dx1Configuration"));
            services.Configure<IdentityServerConfiguration>(Configuration.GetSection("Authentication:IdentityServer"));
            services.AddScoped<Dx1RepositorySession>();
            services.AddScoped<Dx1CurrentUser>();

            //Configure SnapshotCollector from application settings
            services.Configure<SnapshotCollectorConfiguration>(Configuration.GetSection(nameof(SnapshotCollectorConfiguration)));

            //Add SnapshotCollector telemetry processor.
            services.AddSingleton<ITelemetryProcessorFactory>(sp => new SnapshotCollectorTelemetryProcessorFactory(sp));

            DxServiceProvider.SetLogger(
                new DxServerLogger(
                    Configuration["Dx1Configuration:AppInsightsFilter:InstrumentationKey"],
                    Configuration["Dx1Configuration:AppInsightsFilter:AppName"],
                    bool.Parse(Configuration["Dx1Configuration:AppInsightsFilter:EnableTracing"])));

            services.AddSingleton(_ => Configuration);

            //Configure response compression
            services.Configure<GzipCompressionProviderOptions>(options =>
                                                                   options.Level = System.IO.Compression.CompressionLevel.Optimal);
            services.AddResponseCompression(options =>
                                            {
                                                options.Providers.Add<GzipCompressionProvider>();
                                                options.EnableForHttps = true;
                                            });

            // Add Azure SignalR Support
            services.AddSignalR(options => { options.EnableDetailedErrors = true; })
                    .AddAzureSignalR();

            // Add MVC
            services.AddCorrelationId(); // used by the httpclient
            services.AddMvc()
                .AddJsonOptions(
                    options =>
                    {
                        options.SerializerSettings.ContractResolver = new DxContractResolver();
                        options.SerializerSettings.Converters.Add(new StringEnumConverter());

                        /* DxContractResolver will not send null when serialize object, but require to handle null when deserialize json */
                        // options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                    })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_0)
                .Services
                .AddPolicies(Configuration)
                .AddHttpClient<IAzureFunctionClient, AzureFunctionClient, AzureFunctionClientOptions>(Configuration, nameof(Dx1Configuration.AzureFunctionClient));



            // Add Swagger support
            services.AddSwaggerGen(c => { c.SwaggerDoc("v1", new Info { Title = "LSK DMS API", Version = "v1" }); });

            // Add IdentityServer4 Authentication support
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
                .AddCookie("Cookies")
                .AddOpenIdConnect("oidc", options =>
                {
                    options.SignInScheme = "Cookies";

                    options.Authority = Configuration["Authentication:IdentityServer:Authority"];
                    options.RequireHttpsMetadata = false;

                    options.ClientId = Configuration["Authentication:IdentityServer:ClientCredential:ClientId"];
                    options.ClientSecret = Configuration["Authentication:IdentityServer:ClientCredential:ClientSecret"];
                    options.ResponseType = "code id_token";

                    options.SaveTokens = true;
                    options.GetClaimsFromUserInfoEndpoint = true;

                    options.Scope.Add(Configuration["Authentication:IdentityServer:ApiName"]);
                    options.Scope.Add("openid");
                    options.Scope.Add("profile");
                    options.Scope.Add("email");
                    options.Scope.Add("offline_access");
                })
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = Configuration["Authentication:IdentityServer:Authority"];
                    options.RequireHttpsMetadata = false;
                    options.ApiName = Configuration["Authentication:IdentityServer:ApiName"];
                    options.ApiSecret = Configuration["Authentication:IdentityServer:ClientCredential:ClientSecret"];

                    options.EnableCaching = true;
                    options.CacheDuration = TimeSpan.FromMinutes(10); // that's the default
                });

            services.AddSingleton<IConfigureOptions<TelemetryConfiguration>, AppInsightsConfiguration>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public static void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseCorrelationId();
            app.UseAppInsightProcessor();
            app.UseAuthentication();
            app.UseStaticFiles();
            app.UseSignalR(route =>
            {
                route.MapHub<DxCoreHub>("/DxCoreHub");
            });
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.RoutePrefix = string.Empty;
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "API V1");
            });
            app.UseMvc(routes =>
                       {
                           routes.MapRoute(
                               "default",
                               "{controller=Home}/{action=Index}/{id?}");
                       });
        }

And I will get the following error when I try to run

System.InvalidOperationException: 'AddAzureSignalR(...)' was called without a matching call to 'IApplicationBuilder.UseAzureSignalR(...)'.

   at Microsoft.Azure.SignalR.ServiceLifetimeManager`1..ctor(IServiceConnectionManager`1 serviceConnectionManager, IClientConnectionManager clientConnectionManager, IHubProtocolResolver protocolResolver, ILogger`1 logger, AzureSignalRMarkerService marker)

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)

   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)

   at Microsoft.AspNetCore.Connections.ConnectionBuilderExtensions.UseConnectionHandler[TConnectionHandler](IConnectionBuilder connectionBuilder)

   at Microsoft.AspNetCore.SignalR.SignalRConnectionBuilderExtensions.UseHub[THub](IConnectionBuilder connectionBuilder)

   at Microsoft.AspNetCore.SignalR.HubRouteBuilder.<>c__3`1.<MapHub>b__3_0(IConnectionBuilder builder)

   at Microsoft.AspNetCore.Http.Connections.ConnectionsRouteBuilder.MapConnections(PathString path, HttpConnectionDispatcherOptions options, Action`1 configure)

   at Microsoft.AspNetCore.SignalR.HubRouteBuilder.MapHub[THub](PathString path, Action`1 configureOptions)

   at Microsoft.AspNetCore.SignalR.HubRouteBuilder.MapHub[THub](PathString path)

   at Dx1.Web.Startup.<>c.<Configure>b__5_0(HubRouteBuilder route) in C:\LSK\ClientApp\Dx1.Web\Startup.cs:line 164

   at Microsoft.AspNetCore.Builder.SignalRAppBuilderExtensions.<>c__DisplayClass0_0.<UseSignalR>b__0(ConnectionsRouteBuilder routes)

   at Microsoft.AspNetCore.Builder.ConnectionsAppBuilderExtensions.UseConnections(IApplicationBuilder app, Action`1 configure)

   at Microsoft.AspNetCore.Builder.SignalRAppBuilderExtensions.UseSignalR(IApplicationBuilder app, Action`1 configure)

   at Dx1.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\LSK\ClientApp\Dx1.Web\Startup.cs:line 162

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)

   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)

   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)

   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)

   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)

   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()


I do not seem to be having the same issue as above or am I?

any ideas

**Comment by davidfowl** [comment] 2019-06-26 05:21
The exception message explains what the problem is, specifically:

```
System.InvalidOperationException: 'AddAzureSignalR(...)' was called without a matching call to 'IApplicationBuilder.UseAzureSignalR(...)'.
```

You haven't called  `UseAzureSignalR` as a replacement for `UseSignalR` in the Configure method.

**Comment by curtisconner** [comment] 2019-06-26 06:50
Doh, thanks.  amazing the number of hours you waste when the answer is right there.  Again thanks

**Comment by Olusheenor** [comment] 2019-06-27 15:14
I have similar issue but on AspNetcore UseSignalR

**Closed** 2020-08-24 04:58 UTC
Labels: bug
