### ISSUE TITLE
Very strange buffering with messages to a particular group

### ISSUE THREAD

**Issue by Prinsn** [Azure/azure-signalr#963] opened 2020-07-10 13:21 UTC
### Describe the bug
We currently are using SignalR, serverless, to do messaging to our client app.

Everything appears to work fine, and has been working fine, for months.

However, on the latest new Azure Function that we've added, it's been noted that messages targeting group "3" will get buffered until any other group has a message _or_ 3 messages are sent to group 3, at which point the client will receive all messages simultaneously.

It has been otherwise isolated to group 3 (in lieu of actually testing every number, but no one has observed it except on 3, across a random sampling of other numbers), and is _always_ of the same pattern of having 2 messages buffered and the third having all three received by the server.

The client is also connected via what is presented as a websocket in Chrome's dev tools (I don't know if that means it is correctly a WS or if it just displays WS and it can be in any fallback state)

### To Reproduce

I don't have a way to offer reproduction because it's between an angular consumer (as the only means of even being aware that the messages get sent) and the backend which is doing nothing but sending the message, but it is peculiar to the point that it is reproducible in the project itself between multiple team members locally.

After this occurs, the behavior is no longer observed, only recurring on a server restart.

### Exceptions (if any)

No exceptions, or even wrong behavior.  Once the client receives all of its messages, it responds to all of them exactly as if the server just sent three distinct messages.

### Further technical details
- ASP.NET Core version
Dependency is at 2.2.8 for server for both ASP and base .NET Core
Does not exist on the functions, but function dependencies are at 2.2.0 for .NET Core, as well as the SignalR project.
For the project, SignalR.Management is at 1.2.3, Azure.WebJobs.Extensions.SignalRService is at 1.0.2, and Azure.ServiceBus as 4.1.1

### Further technical details
- Your Azure SignalR SDK version
For the project, SignalR.Management is at 1.2.3, Azure.WebJobs.Extensions.SignalRService is at 1.0.2,
I'm not seeing anything for an SDK proper, NuGet viewer at the solution level only lists those two as installed.

- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` 
2.2

- Your SignalR Client SDK version
"@aspnet/signalr": "^1.1.4",

**Comment by wanlwanl** [comment] 2020-07-14 09:54
Hi @Prinsn Could you send me your SignalR service's resource ID, and give me the code snippets on how you
- join group
- leave group
- send group messages?
I'll try to reproduce it first.

**Comment by Prinsn** [comment] 2020-07-14 13:50
Emailed regarding resource ID.

Snips:

Send
```CSharp
        protected async Task SendSignalRMessage(string method, string group, params object[] parameters)
        {
            if (!int.TryParse(group, out _))
            {
                throw new ArgumentException("Group name for signalR messages must be a valid integer");
            }

            LogInfo($"Sending SignalR message to {method}");

            var exception = await SignalRHelpers.SendMessageToGroup(
                Settings.SignalRConnectionString(),
                group,
                SignalRConstants.HUB_NAME,
                method,
                parameters
            ).ConfigureAwait(false);

            if (exception != null)
            {
                LogException(exception);
            }
        }```

Setup, join/leave
```typescript
import { Injectable } from '@angular/core';
import { HubConnection, HubConnectionBuilder, HubConnectionState, LogLevel } from '@aspnet/signalr';
import Utilities from '../utilities';
import { Subject } from 'rxjs';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { OpenIdConnectService } from '../open-id-connect/open-id-connect.service';
import { ServerSideConfigDataService } from '../server-side-config-data/server-side-config-data.service';

@Injectable({
    providedIn: 'root'
})
export class SignalRService {
    private endpoint: string;
    private connection: HubConnection;

    //Omitted for brevity
    //msgReceiveHandler$ = new Subject<string>();

    constructor(
        private http: HttpClient,
        private oidcService: OpenIdConnectService,
        private serverSideData: ServerSideConfigDataService
    ) {
    }

    get connected(): boolean {
        return this.connection
            && this.connection.state == HubConnectionState.Connected;
    }

    public init(): Promise<void> {
        if (this.connected) {
            return Promise.resolve();
        }

        this.endpoint = this.serverSideData.configData.signalREndpoint;
        const token = this.oidcService.user.access_token;

        const builder = new HubConnectionBuilder()
            .withUrl(this.endpoint, {
                accessTokenFactory: () => token
            });

        this.connection = builder.build();
        this.initializeSubscriptions();
        this.disconnectHandlingAttempts();
        return this.ensureConnection();
    }

    private initializeSubscriptions() {
        //ommitted for brevity
        //this.connection.on("msgName", this.handlerFn.bind(this));
    }

    private disconnectHandlingAttempts() {
        this.connection.onclose(err => {
            if (err) {
                console.error("SignalR disconnected due to an error:", err);
            }
        });

        this.connection.serverTimeoutInMilliseconds = 5 * 60 * 1000;
        this.connection.keepAliveIntervalInMilliseconds = 10 * 1000;
    }

    private modifySignalRGroup(projectionId: number, action: "add" | "remove") {
        this.http
            .post(
                `${this.endpoint}/groups/${action}`,
                {
                    projectionId: projectionId.toString()
                },
                {
                    headers: new HttpHeaders({
                        authorization: `Bearer ${this.oidcService.user.access_token}`
                    })
                }
            )
            .toPromise()
            .then(() => {
                if (action == "add") {
                    console.log(`Subscribed to ${projectionId}`);
                } else if (action == "remove") {
                    console.log(`Unsubscribed from ${projectionId}`);
                }
            });
    }

    public subscribe(id: number) {
        this.modifySignalRGroup(id, "add");
    }

    public unsubscribe(id: number) {
        this.modifySignalRGroup(id, "remove");
    }

    // Instances of multiple simultaneous connection attempts were observed
    private connectionLock = false;
    ensureConnection(): Promise<void> {
        if (this.connection.state == HubConnectionState.Disconnected && !this.connectionLock) {
            this.connectionLock = true;
            return this.connection.start()
                .finally(() => {
                    this.connectionLock = false;
                });
        }

        return Promise.resolve();
    }
}
```

Of note that in the particular case of this problem, the group is never joined, which is a part that is confusing us otherwise, as we would expect to not receive the message if the group in question was not subscribed to?

The provided subscriptions are in use for other features, distinct from the current case that I've run into

**Comment by wanlwanl** [comment] 2020-07-14 14:35
The REST APIs are incorrect in your code snippet: you can find all REST APIs [here](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.md#put-add-a-connection-to-the-target-group). We have REST APIs for join/leave user/connection to/from group.

You mention that `only recurring on a server restart` - is the function app (since you said it's in serverless environment) ?

You issue might be every components: SignalR service, Azure function, SignalR client.
Let's check each part one by one to locate the root cause.
Let's check SignalR service first: please use this [Management sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Management) (by default user ID: User) to join and send message to group "3" to see whether the problem still occur or not. I tried myself with my own SignalR service, everything works well.

You mentioned `It has been otherwise isolated to group 3`. How you do the test? have you change the order the groups you test? The function app needs some time to completely setup, and if you use `Persistent` mode (by default: `Transient` mode) in SignalR extension or Management SDK, it take some time to establish connection. How much time you wait until you get the first message? You can try `transient` mode, it simply sends http requests. More details can be found [here](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#transport-type).

Could you also share the function `SignalRHelpers.SendMessageToGroup`?

**Comment by vicancy** [comment] 2020-08-24 04:53
Closing the issue as the root cause is found and the solution is provided, please feel free to reopen the case if you still have concerns about the answer provided.

**Closed by vicancy** 2020-08-24 04:53 UTC
