### ISSUE TITLE
Response status code does not indicate success: 429 (Too Many Requests).

### ISSUE THREAD

**Issue by gynet** [Azure/azure-signalr#258] opened 2018-11-08 21:57 UTC
I am using Azure signalR 1.0.0, on the client side i received this error

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SignalRExperimentClient.Program.Init() in D:\SignalRExperiment\SignalRExperimentClient\Program.cs:line 61
   at SignalRExperimentClient.Program.Main(String[] args) in D:\SignalRExperiment\SignalRExperimentClient\Program.cs:line 21

Inner Exception 1:
HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).

**Comment by gynet** [comment] 2018-11-08 21:58
Is the server connection number count as the total?

**Comment by vwxyzh** [comment] 2018-11-09 02:17
> Is the server connection number count as the total?

Yes.

**Comment by torhovland** [comment] 2019-04-01 13:31
We're also getting a lot of HTTP 429 on negotiation requests. This happens even when we have stayed well below 20 server connections for the last few hours, and far below 20.000 messages per day. Are there any other limits I need to be aware of, such as connection requests per minute, or similar?

**Comment by tomaszlubocki** [comment] 2019-04-10 14:09
HI All, Im getting exactly the same issue lot of negotiation problem. I call the AzureSignalR from AzureFunc which triggered by storage queue trigger.

**Comment by dwlodarz** [comment] 2019-04-11 12:56
Any update on this issue? I'm experiencing very same problem

**Comment by tomaszlubocki** [comment] 2019-04-11 15:10
> HI All, Im getting exactly the same issue as @torhovland -> lot of negotiation problems, 429. I call the AzureSignalR from AzureFunc which triggered by storage queue trigger.

I solved my problem. Since yesterday all my messages reached the destination. The key was https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-internals

The client -sever relation is 1:1 from perspective of the client, and I had two servers one of them was not negotiating properly. 

Solution : using azure func with serverrless Azure SignalR Component, in the web part I have singal R only on frontend poiting do azure func absolute url.

**Comment by vicancy** [comment] 2020-08-24 05:05
Closing the issue as the root cause is found and 429 is expected.

**Closed by vicancy** 2020-08-24 05:05 UTC
