### ISSUE TITLE
Closing server connection when debugging

### ISSUE THREAD

**Issue by steve-79** [Azure/azure-signalr#242] opened 2018-10-23 02:28 UTC
I have one single hub, but each time I start my program in visual studio, Azure SignalR uses 20 server connections.  Then if I stop debugging and try to debug again, this number jumps to 30 and maxes out the free plan, so then I receive the "Connection count reaches limit."

I have to completely exit visual studio and close all of the tabs I'm debugging in and wait a couple minutes to restart visual studio for the Azure Signal R server count to go back to 0....am I doing something wrong?  My client connections are always at 0, or match what they should be but it looks like the server connection count is adding in increments of 20 and I can't find any way to shut them all when they max out at 30 without exiting visual studio and re-opening it.  

It's like I'm missing a server close hub method or something for when I stop debugging.

_Originally posted by @steve-79 in https://github.com/Azure/azure-signalr/issues/234#issuecomment-432024836_

**Comment by zackliu** [comment] 2018-10-23 02:54
When you stop debugging, visual studio should close the app server and server connections will be closed immediately. I can't reproduce the problem you mentioned. Maybe the visual studio you're using doesn't close the dotnet.exe when stop debugging. You can go to Task Manager -> Details and end dotnet.exe manually.

**Comment by vicancy** [comment] 2018-11-07 09:50
I am closing the issue, if you have additional concerns, please feel free to reopen it.

**Closed by vicancy** 2018-11-07 09:50 UTC

**Comment by steve-79** [comment] 2018-11-07 16:55
Sorry for such a delayed reply, you are correct.  Visual Studio doesn't appear to be closing the dotnet.exe when stopping debugging.  For anybody else having issues like this, when you publish your web app from Visual Studio, make sure to exit Visual Studio in order to close the connections and not use any connections from the live app you just published.

**Comment by andegre** [comment] 2020-07-16 06:33
Wow, this is still an issue with VS2019 Enterprise Edition!
