### ISSUE TITLE
The SDK having issue to reach out to Azure SignalR - The connection is not active, data cannot be sent to the service.

### ISSUE THREAD

**Issue by gynet** [Azure/azure-signalr#222] opened 2018-10-03 17:00 UTC
I am having a signalR service to be used send message to a group of clients. So basically, I was testing with only one client connecting to the server overnight,. 

The server instance running overnight, in the morning, I try to push a message to a group client again, it failed and I saw this issue  on the sever side, it's having this error multiply times. 

--------------------------------------------------------------------------------------
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[18]
      Service timeout. 30000.00ms elapsed without receiving a message from service.
fail: Microsoft.Azure.SignalR.ServiceConnection[6]
      Error while sending message to the service.

System.InvalidOperationException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
fail: Microsoft.Azure.SignalR.ServiceConnection[6]
      Error while sending message to the service.
System.InvalidOperationException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
fail: Microsoft.Azure.SignalR.ServiceConnection[6]
      Error while sending message to the service.
System.InvalidOperationException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
fail: Microsoft.Azure.SignalR.ServiceConnection[6]
      Error while sending message to the service.
System.InvalidOperationException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
fail: Microsoft.Azure.SignalR.ServiceConnection[6]
      Error while sending message to the service.

----------------------------------------------------------------------------------------------------

From the client side, I saw it got reconnected once over night. 

Just FYI,  i did not add the code to join the group once it reconnected , so that means it could send message to a group which no clients exists, not sure if that cause the issue.

**Comment by gynet** [comment] 2018-10-03 17:54
On the signalr client side, if I reconnect to our server.  it got error: 

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SignalRExperimentClient.Program.Init() in D:\SignalRExperiment\SignalRExperimentClient\Program.cs:line 62
   at SignalRExperimentClient.Program.Main(String[] args) in D:\SignalRExperiment\SignalRExperimentClient\Program.cs:line 19

Inner Exception 1:
HubException: The server closed the connection with the following error: No server available.

**Comment by gynet** [comment] 2018-10-04 16:57
I retried yesterday with three clients and had the same issue. 
Server side: 
System.InvalidOperationException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
fail: Microsoft.Azure.SignalR.ServiceConnection[6]
      Error while sending message to the service.


Client side: 

Connected to the server
------------------------------------- Connection closed -------------------------------------

Unhandled Exception: Microsoft.AspNetCore.SignalR.HubException: The server closed the connection with the following error: No server available.
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
Try to reconnected to the server
System.AggregateException: One or more errors occurred. (The server closed the connection with the following error: No server available.) ---> Microsoft.AspNetCore.SignalR.HubException: The server closed the connection with the following error: No server available.
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SignalRExperimentClient.Program.Init() in D:\SignalRExperiment\SignalRExperimentClient\Program.cs:line 64
   at SignalRExperimentClient.Program.Main(String[] args) in D:\SignalRExperiment\SignalRExperimentClient\Program.cs:line 21

**Comment by vicancy** [comment] 2018-10-04 23:54
According to the error message, there is no server connection available because server is not receiving heartbeat from Azure Service. Could you provide your instance name and time when the issue took place through email for us to take a look at the service log?

**Comment by vicancy** [comment] 2018-10-08 02:52
The service log shows that the Azure service aborts the server connection as it believes the server connection times out. We are investigating the root cause and will give you an update as soon as we have the answer and a remedy for it. cc @vwxyzh

**Comment by maxiptah** [comment] 2018-10-08 14:01
We have the same here. Occasionally a web app backed up by Azure SignalR would throw this:

`ERROR|CentralExceptionHandler|Central exception: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnectionManager`1.WriteAsync(ServiceMessage serviceMessage)
  at <... custom hub code ...>`

This is preceded by:
`2018-10-07 08:33:21.3487||2|ERROR|Microsoft.Azure.SignalR.ServiceConnection|Failed to connect to the service. System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.Azure.SignalR.ServiceHubDispatcher`1.ConnectAsync(TransferFormat transferFormat, String connectionId, CancellationToken cancellationToken)
   at Microsoft.Azure.SignalR.ServiceHubDispatcher`1.ConnectAsync(TransferFormat transferFormat, String connectionId, CancellationToken cancellationToken)
   at Microsoft.Azure.SignalR.ServiceConnectionBase.StartAsyncCore()`

and also by multiple:

`2018-10-07 08:32:39.1740||18|ERROR|Microsoft.Azure.SignalR.ServiceConnection|Service timeout. 30000.00ms elapsed without receiving a message from service.`

There is no client connection interested in the message at all at the moment (we see exception in automated tests, no UI), the server is posting a message to an empty group like this:
`await this.ctx.Clients.Groups("myEmptyGroup").SendAsync("clientMethod");`

And this normally works, but fails every other day a couple of times.

**Comment by vicancy** [comment] 2018-10-08 14:42
@maxiptah Can you check if the ping messages are successfully sent to service by switch server side log level to `Debug` mode when the error happens? https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Common/ServiceConnectionBase.cs#L401  
It is possible that **threadpool starvation** took place on the app server side, that [TrySendPingAsync](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Common/ServiceConnectionBase.cs#L385) fails to be evoked within 30 seconds, and causing Azure service to believe the server is down, and aborted the connections, and as a result the app server can not receive the ping message from the service.

**Comment by vicancy** [comment] 2018-10-08 15:02
You can also capture a dump following https://github.com/aspnet/KestrelHttpServer/issues/2284#issuecomment-427551094

**Comment by maxiptah** [comment] 2018-10-08 15:05
@vicancy This server is in developent and does run at debug logging level. If I understand it right, in this case I would see "Failed sending a ping message to service." in my logs, but that's not the case, the message does not appear in the logs for the day when error occured.

**Comment by vicancy** [comment] 2018-10-09 01:33
@maxiptah no, not “Failed sending ping”, but PingSent **on time**. So what we are looking for is PingSent log during that period when error occurs and check if the log time is every 15 seconds.

**Comment by maxiptah** [comment] 2018-10-09 07:18
@vicancy ok, got it. Found out that Microsoft logs were turned off in our project, so cannot give you feedback. I've enabled these logs now, have a lot of "pinging" going on. I'll keep an eye on it for a couple of days and report back when/if the error occurs again.

**Comment by maxiptah** [comment] 2018-10-16 13:45
@vicancy  So finally I could get some logs (the problem occured 8 times in 7 days on a constantly running development server) - see attached file. Yes, it looks like SignalR cannot reach the server after 30 seconds. But what do I make of it? All application logs surrounding the error seem fine (e.g. performance middleware logs REST API calls times well under 1 second). After some time SignalR logs that connection was reestablished. We are using an Azure hosted webapp with Azure SignalR.

Does this mean that this exception is expected? Should I wrap my call to hubContext.Clients... with a try-catch and catch InvalidOperationException? What other exceptions should I expect?

In Azure Metrics for SignalR I see user errors (not system errors) for this timespan on the chart. I cannot see what the errors are, just that they took place. Does the issue has to do with Azure infrastructure or with the library?

[SignalRLog.txt](https://github.com/Azure/azure-signalr/files/2483267/SignalRLog.txt)

**Comment by vicancy** [comment] 2018-10-17 02:49
Hi @maxiptah 

The first exception is not expected, it generally indicates that the app server side is experiencing thread-starving(can happen when thread-pool threads are all blocked) or timer queue busy(can happen when `HttpClient` is not disposed) or other issues. Could you capture a dump file for that server so that we can take a deep look why the *ping message* is not sent on time, following https://github.com/aspnet/KestrelHttpServer/issues/2284#issuecomment-427551094? 

>**2018-10-15 09:39:35.3100**||25|DEBUG|Microsoft.Azure.SignalR.ServiceConnection|Sent a ping message to service. 
2018-10-15 09:39:35.3100||16|DEBUG|Microsoft.Azure.SignalR.ServiceConnection|Received 3 bytes from service ce50c402-fa4f-4729-b07f-96bc0f72a748. 
...
**2018-10-15 09:40:10.2754**||18|ERROR|Microsoft.Azure.SignalR.ServiceConnection|Service timeout. 30000.00ms elapsed without receiving a message from service.  

The second one shows the connection is closed, is the log time UTC? Could you email me `lianwei<at>microsoft.com`(`<at>` to `@`) your instance name so that I can check the service side log what is going on? If it is Free-tier service, it can happen when message limit reaches.
> 2018-10-15 09:44:29.7189||14|DEBUG|Microsoft.Azure.SignalR.ServiceConnection|Service connection cb6ed064-7b17-415c-bb26-c21a2f60ad0b closed.

**Comment by maxiptah** [comment] 2018-10-17 07:20
Hi @vicancy 
Capturing a dump is complicated, because I see these exceptions in logs, when everything is already running normally. The app is using HttpClientFactory so this should not be a problem. We had some starving situations when lots of long running REST requests were coming, but that had a totally different pattern: everything was getting slow and app didn't recover. What I see now is that only SignalR is having problems, whilst other requests are running normally and executing fast.

**Comment by lbargery** [comment] 2018-10-18 08:36
@maxiptah I'm getting similar exceptions go off every so often. I get one that looks the same as yours and one slightly different one. Both exceptions below:

1.
The connection is not active, data cannot be sent to the service.
Type
`InvalidOperationException`
Stack Trace
   ```at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)```
Exception
```System.InvalidOperationException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)```

2.
The remote party closed the WebSocket connection without completing the close handshake.
Type
`WebSocketException`
Stack Trace
   ```at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()```
Exception
```System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()```

**Comment by gynet** [comment] 2018-10-18 22:45
Hi Liangying @vicancy,

Looks like other ppl have similar issue too, is there any update from your team about this issue?

George

**Comment by vicancy** [comment] 2018-10-19 04:00
This kind of error message happens when service side fails to receive the ping message within 30 seconds. Different cases can lead to such errors. 

Hi @lbargery , could you capture a dump file as I suggested in https://github.com/Azure/azure-signalr/issues/222#issuecomment-430470729 so that we can identify what caused the *exception number 1*? *Exception number 2* looks like the websocket channel is not closed correctly, we will take a look.

Hi @gynet, for your case, as the dump shows, it is your third party logging tool not disposing HttpClient correctly that causing the issue. Could you try if you can repro the issue when running your app server code locally for 24 hours? I believe you can also try a  simpler repro step by, creating a simple console app with your logging tool, and a timer runs and checks if it is triggered on time, sudo code here https://gist.github.com/vicancy/c9eac0789f8b38da77bd23cd6a409eef

**Comment by lbargery** [comment] 2018-10-19 08:54
@vicancy Sure happy to capture this! How do i do that on my azure web app? They go off on our production and demo servers every day at some point so should be easy to capture.

**Comment by lbargery** [comment] 2018-10-22 14:15
@vicancy Thanks will do this. Does it need to be done pretty much straight away after the exception goes off? Slightly hard to do since I can't force the exception, it just seems to happen sporadically during the day.

**Comment by vicancy** [comment] 2018-10-23 05:30
@lbargery No need to right after the exception, one after the exception and before the App server restart can be useful

**Comment by lbargery** [comment] 2018-10-23 08:44
@vicancy This dump is from just after the exception went off yesterday. Let me know if haven't got this right or you need more.

https://accurx-my.sharepoint.com/:u:/p/laurence/ERHs0SA0scZCtBTp03Vq5xIBwmpakksRRDBUN1FnO0cc7g?e=ZyYxZX

**Comment by vicancy** [comment] 2018-10-24 05:44
@lbargery I am not able to Debug Managed Memory because the garbage collection was in progress. 😿 
![image](https://user-images.githubusercontent.com/668244/47408638-c67bcf80-d792-11e8-9b72-dda076731918.png)
Could you have another try? You can open the dmp file directly from Visual Studio, and select "Debug Managed Memory" action to view the managed heap.
![image](https://user-images.githubusercontent.com/668244/47408691-f5924100-d792-11e8-9e26-91020c7a40c1.png)

**Comment by lbargery** [comment] 2018-10-24 10:49
Sure! Will try again when it goes off today/tomorrow

**Comment by lbargery** [comment] 2018-10-25 09:00
Hi @vicancy have tried again. Here the first dump is 3 mins after crash then took one 10 mins after that. Hope this works this time! https://accurx-my.sharepoint.com/:f:/p/laurence/EnMgQiJbNFhDk6tTIr4JSS0BZzQaU-oCFmEXChDmgxX7cg?e=bVpAah

**Comment by lbargery** [comment] 2018-10-25 14:57
Also am seeing occasionally the signalR service going completely down for a long time. I did raise a ticket originally with azure about this but not sure best place to chat on it. Have attached screenshot

![image](https://user-images.githubusercontent.com/5844039/47509754-a4577f80-d86e-11e8-9951-231e0f26b182.png)

**Comment by lbargery** [comment] 2018-10-29 10:35
@vicancy Not sure why our GC would be any different to normal, we're just using a normal azure web app. We had 3 days just now when no clients could connect to the hub. On the advice of someone at Azure we then scaled down to free and back up to paid. This then meant that the server also lost connection to the hub. We then changed the connection string to the secondary key which seemed to fix things for the moment. Are these production issues being seen by others/known about? Really keen to keep using the service but the connection drops are causing us a lot of production issues at the moment.

![image](https://user-images.githubusercontent.com/5844039/47644514-3bba1c80-db66-11e8-8a3f-f0cf62930cd9.png)

**Comment by vicancy** [comment] 2018-10-30 03:07
Hi @lbargery Clients unable to connect should be another issue, could you email me `lianwei<at>microsoft`(`<at>` to `@`) your instance name for me to have a check?

**Comment by lbargery** [comment] 2018-10-30 10:19
Done, thanks!

**Comment by gynet** [comment] 2018-10-30 17:33
@vicancy I am trying to reaching out to Asimov team to investigate, but at the same time, I wonder if there any clue to indicate the httpclient leaking issue causing by the logging tool, or if it's possible it could be caused by the Azure SignalR SDK since it is always trying to reconnect to Azure? Our service and some other teams have been using the tool for a while and we do not see any issue about process requests.

**Comment by vicancy** [comment] 2018-10-31 02:19
@gynet no, we don't create `HttpClient` for server side connections.

**Comment by Jos1k** [comment] 2018-11-04 16:42
In fact we have the same issue ("The connection is not active, data cannot be sent to the service") when try to send message to the user group:
![last_load_signalr](https://user-images.githubusercontent.com/8057480/47966964-3a9e5900-e058-11e8-86a3-d3d4c5657c33.png)

In addition I receive an error during the client (angular) is trying to connect:
First time client is trying to connect receives such error:
![first_load_signalr](https://user-images.githubusercontent.com/8057480/47966893-95838080-e057-11e8-9b0b-724dd82fa08d.png)

Each next connection client receives error:
![next_load_signalr](https://user-images.githubusercontent.com/8057480/47966896-99170780-e057-11e8-8212-2d0c4cede278.png)

In Startup.cs I have configuration regarding signalR such:
```
public void ConfigureServices(IServiceCollection services){
.....
services.AddCors(o => o.AddPolicy("CorsPolicy", builder =>
            {
                builder
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowAnyOrigin()
                    .AllowCredentials();
            }));
            var signalRBuilder = services.AddSignalR();

            if (!Environment.IsDevelopment())
            {
                signalRBuilder.AddAzureSignalR(
                    $"Endpoint={_configuration.SignalR.Url};AccessKey={_configuration.SignalR.AccessKey}");
            }
....}

public void Configure(IApplicationBuilder app, IHostingEnvironment env){
....
            app.UseCors("CorsPolicy");

            if (env.IsDevelopment())
            {
                app.UseSignalR(r => r.MapHub<RequestsHub>("/community/live-notifications"));
            }
            else
            {
                app.UseAzureSignalR(r => r.MapHub<RequestsHub>("/community/live-notifications"));
            }
           
            app.UseMvc();
}
```

**Comment by vicancy** [comment] 2018-11-07 09:34
Hi @Jos1k please open another issue for us to track it.

**Comment by lbargery** [comment] 2018-11-21 15:52
Hey @vicancy - any progress on this? We still see our hub drop all its connections and get the same errors documented above a couple of times a day. Will be pushing out version 1.0.3 of the SDK to prod over next few days but main changes looked like re-connect?

**Comment by vicancy** [comment] 2018-11-22 08:51
Hi @lbargery We are working on several fixes to reduce the chance of meeting this kind of issue, you can update to the latest SDK to see if it helps.
1. The latest SDK makes the change to always re-connect, this might be helpful to your case. The server connection will always try to reconnect. Before that, if handshake fails, that server connection is dead.
1. https://github.com/Azure/azure-signalr/pull/268/files/573066f068a261f39f8df2d8d0e90eb63039d39b..7a73d7282530f4e6eb603b67654a04e61fc35c7a which will mitigate the server side ping message issue. 
1. https://github.com/Azure/azure-signalr/issues/270 which will prevent the unhealthy connection from being chosen

**Comment by kaiokot** [comment] 2018-12-27 17:11
Hi, any updates? 
I'm getting this error today on my production environment "The connection is not active, data cannot be sent to the service."
I'm using Microsoft.Azure.SignalR 1.0.5;
Tks

**Comment by vicancy** [comment] 2018-12-28 02:49
HI @kaiokot this error can happen when the server connection is closed, due to for example network issue. Is the error persistent or the app server recovered? Do you have any other log indicating what happened to the server connection? 

I am going to close this issue as the original issue created by @gynet is resolved.
Please open new issue to track if you encounter similar issue.

**Closed by vicancy** 2018-12-28 02:49 UTC
Labels: question

**Comment by kaiokot** [comment] 2019-03-01 14:24
Hi, What was the solution?

**Comment by vicancy** [comment] 2019-03-04 02:37
Hi @kaiokot This can happen when server connection drops. Server connections will automatically reconnect, so in general you don't have to do anything. Server connection drops can happen when for example, network issues, service machine relocate, etc. If you see such connection drops too often, that is abnormal, please open a ticket for us to take a look.

**Comment by AhsanKhan-Marn** [comment] 2023-09-29 11:38
https://github.com/Azure/azure-signalr/issues/222#issuecomment-427101768

**_I have been facing the same issue for 2 last days_**
