### ISSUE TITLE
CryptoProviderFactory - memory leak on Identity

### ISSUE THREAD

**Issue by molekm** [Azure/azure-signalr#654] opened 2019-09-10 13:08 UTC
CryptoProviderFactory from Microsoft.IdentityModel.Tokens.JWT version 5.5.0 & 5.4.0 

![image](https://user-images.githubusercontent.com/52691210/64616285-2cd20680-d3d4-11e9-8553-7c31accc7375.png)

I saw the other ticket that was supposed to be fixed in 5.5.0, however looks like there is still a possible memory leak in CryptoProviderFactory (InMemoryCryptoProviderCache). Both in 5.5.0 & 5.4.0.

5.3.0 is working fine.

**Comment by JialinXin** [comment] 2019-09-11 03:07
Refer to #647 . This issue is caused by a change in Microsoft.IdentityModel.Tokens.JWT version 5.5.0. The code fix is done and will be in the coming release.

**Closed** 2019-09-11 06:28 UTC

**Comment by molekm** [comment] 2019-09-12 07:15
Well I cannot as we are using Microsoft.IdentityModel.Tokens.JWT directly.

5.3.0 is still last working version.

Is there any other github for JWT Tokens that I can create this issue ?

**Comment by JialinXin** [comment] 2019-09-12 07:26
Refer to #647. You can either disable signature provider caching in your side or provide feedback to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
