### ISSUE TITLE
AddAzureSignalR() seems to be causing all results to be null in the response frames

### ISSUE THREAD

**Issue by stephenweaver** [Azure/azure-signalr#132] opened 2018-06-21 17:29 UTC
Hi, I'm seeing a strange issue that wasn't happening a couple days ago when I started using azure-signalr. 

Whenever I append .AddAzureSignalR() to services.AddSignalR() in ConfigureServices, all the frames of the incoming messages have null in the result.

> {"type":3,"invocationId":"0","result":null}
> {"type":3,"invocationId":"1","result":null}
> {"type":3,"invocationId":"2","result":null}
> ...

The other day this was working, and I could see responses from both hubs (even posted screen shots on ticket 124). Currently though, neither hub works if UseAzureSignalR() is added. Even if UseAzureSignalR is removed, the normal hub still gets null results. If I remove AddAzureSignalR() from ConfigureServices, then the results all go start working as expected.

```
app.UseSignalR(routes =>
{
    routes.MapHub<SignalRHub>("/signalr/hub");
});

// even if i remove this the normal hub doesn't work either 
app.UseAzureSignalR(routes =>
{
    routes.MapHub<SignalRHub>("/signalr/azurehub");
});
```

client-lib: aspnet/signalr: 1.0.0,
server-libs: Microsoft.AspNetCore.SignalR: 1.0.1, Microsoft.Azure.SignalR: 1.0.0-preview1-10012 (also tried 10011 which is was i was using the other day, but it didn't work either.)

[client-logs.txt](https://github.com/Azure/azure-signalr/files/2124646/client-logs.txt)
[server-logs.txt](https://github.com/Azure/azure-signalr/files/2124647/server-logs.txt)

Thanks for any insights you can provide

**Comment by xscript** [comment] 2018-06-22 03:11
@stephenweaver I saw serveral issues in your case.

- You can't call `UseSignalR` and `UseAzureSignalR` in a mixed way. `AddAzureSignalR` will replace the underlying dependencies, so `UseSignalR` won't work.
- I saw you have sent message with size larger than 32 KB. Right now we have a limit when you send message from server to clients. The largest size is 32 KB. You can send message with size > 32 KB from client to server though.

Could you confirm it works if you remove `UseSignalR`?

**Comment by stephenweaver** [comment] 2018-06-22 13:50
@xscript  

- Thanks, I didn't realize that you couldn't use both.

- Is this the payload and error that you'd expect to see if a single message size if over 32 KB? 

> {"type":7,"error":"Unknown error."}
>
> Utils.js:148 Error: Connection disconnected with error 'Error: Server returned an error on close: Unknown error.'.

- Is there any configuration to allow a larger message size? Or at least not cause the connection to close?

**Comment by xscript** [comment] 2018-06-22 15:24
> Is this the payload and error that you'd expect to see if a single message size if over 32 KB?
> >{"type":7,"error":"Unknown error."}�
> >Utils.js:148 Error: Connection disconnected with error 'Error: Server returned an error on close: Unknown error.'.

Yes. This error is caused by server connection close. We will improve the error message.

> Is there any configuration to allow a larger message size? Or at least not cause the connection to close?
Not for now. The limitation of message size is at service side. Right now we don't plan to increase it or allow custom configuration. We need some discussion and more testing to help us decide.

Also we have planned a change in Service SDK to check the size of each message before sending to service. Exception will be thrown instead of closing the connection.

> Why is this a limitation of azure signalr service and not signalr? Seems a little bit arbitrary

SignalR has the same limitation. See https://github.com/aspnet/SignalR/issues/2483 . The difference is you can increase the max buffer size as mentioned at [here](https://github.com/aspnet/SignalR/issues/2483#issuecomment-397096356).

**Comment by stephenweaver** [comment] 2018-06-22 15:56
@xscript It doesn't look like the default is 32KB. I've been using payloads larger than that for years without any issues and without overriding anything.

```
app.UseSignalR(routes =>
{
      routes.MapHub<SignalRHub>("/signalr/hub");
});
```

Just ran a simple test to confirm as well. It eventually failed at 18MB, due to taking to a  Server timeout elapsed error.

```
Utils.js:158 Debug: Starting HubConnection.
Utils.js:158 Debug: Starting connection with transfer format 'Text'.
signalr/azurehub/negotiate
vue.js:7874 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
Utils.js:158 Debug: Selecting transport 'WebSockets'
Utils.js:158 Trace: (WebSockets transport) Connecting
signalr/azurehub?id=r1NKxLlid43025el1Dxhxw
Utils.js:158 Debug: Sending handshake request.
Utils.js:158 Trace: (WebSockets transport) sending data. String data of length 32.
Utils.js:154 Information: Using HubProtocol 'json'.
Utils.js:158 Trace: (WebSockets transport) sending data. String data of length 71.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 3.
Utils.js:158 Debug: Server handshake complete.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 40.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 136576.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 273108.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 409640.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 546176.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 682708.
...
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 1911508.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 2048040.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 2184576.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 2321108.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 2457640.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 2594176.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 2730708.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 2867240.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 3003776.
...
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 4232576.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 4369108.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 4505640.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 4642176.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 4778708.
...
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 6690176.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 6826708.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 6963240.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 7099776.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 7236308.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 7372840.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 7509376.
...
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 10376576.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 10513108.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 10649640.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 10786176.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 10922708.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 11059240.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 11195776.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 11332308.
...
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 15018708.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 15155240.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 15291776.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 15428308.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 15564840.
...
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 18022440.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 18158976.
Utils.js:158 Trace: (WebSockets transport) data received. String data of length 18295508.
Utils.js:158 Trace: (WebSockets transport) socket closed.
Utils.js:148 Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.
ConsoleLogger.log @ Utils.js:148
(anonymous) @ HttpConnection.js:317
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
(anonymous) @ tslib.es6.js:65
initializePromise @ es6-promise.js:459
Promise @ es6-promise.js:871
__awaiter @ tslib.es6.js:61
HttpConnection.stopConnection @ HttpConnection.js:311
transport.onclose @ HttpConnection.js:149
webSocket.onclose @ WebSocketTransport.js:61
signalr.js:96 Error: Server timeout elapsed without receiving a message from the server.
    at HubConnection.serverTimeout (HubConnection.js:311)
    at HubConnection.js:305
```

**Comment by xscript** [comment] 2018-06-22 16:08
Yeah, it gets tricky when using Azure SignalR Service.

In ASP.NET Core SignalR, you can observe the limitation from client. It means you can't send a message larger than 32KB from client to server. But you can send message larger than 32KB from server to client.
The reason is server has a pre-defined buffer size (default value is 32KB) to receive message. When message from client exceeds the buffer size, an exception will be thrown.

Then in Azure SignalR Service, your app server is essentially a client to service. Then the 32KB limitation kicks in when you want to send a message from server to client.

**Comment by stephenweaver** [comment] 2018-06-22 16:18
@xscript I see, so the server to client limitation is new. I guess I've never needed a very large payload from client to server. Thanks for the explanation. Do you seen that limit ever changing? If not, we're going to start investigating moving away from signalr, since we've been having issues with 1006 errors ever since we moved to .net core (https://github.com/aspnet/SignalR/issues/2150). We were hoping that using the signalr service would solve our problems, but it seems like it would take quite a bit of re-work to keep our payloads that small.

**Comment by davidfowl** [comment] 2018-06-22 16:35
The limit from the server to the service can be easily fixed and we should fix it.

> If not, we're going to start investigating moving away from signalr, since we've been having issues with 1006 errors ever since we moved to .net core (aspnet/SignalR#2150)

I'm curious, you were using ASP.NET SignalR before and saw no problems right? I have 2 a couple of guesses on what you might be experiencing if that's the case.

**Comment by stephenweaver** [comment] 2018-06-22 16:47
@davidfowl 
>The limit from the server to the service can be easily fixed and we should fix it.

That would be awesome! 

>I'm curious, you were using ASP.NET SignalR before and saw no problems right? I have 2 a couple  of guesses on what you might be experiencing if that's the case.

Correct, we were running ASP.NET SignlaR on this particular application for about a year without any issues. Now were seeing the 1006 error about ~1000 time per day. Would love to hear your couple of guesses.

**Comment by davidfowl** [comment] 2018-06-22 17:09
> Correct, we were running ASP.NET SignlaR on this particular application for about a year without any issues. Now were seeing the 1006 error about ~1000 time per day. Would love to hear your couple of guesses.

I've been discussing this with @anurse for a bit and now I'm thinking that the issue is ANCM (The ASP.NET IIS Module). The fact that it's out of process and there's an outbound connection from w3wp.exe to dotnet.exe for each client websocket connection may be causing issues.

**Comment by stephenweaver** [comment] 2018-06-22 18:11
@davidfowl, 
>I've been discussing this with @anurse for a bit and now I'm thinking that the issue is ANCM (The ASP.NET IIS Module). The fact that it's out of process and there's an outbound connection from w3wp.exe to dotnet.exe for each client websocket connection may be causing issues.
 
>from @anurse on other ticket: in the meantime I would still recommend you explore the Azure SignalR Service. We've previously done tests on VMs and achieved well over 100,000 concurrent connections, so I think this is most likely an issue localized to Azure App Service, in which case either VMs or Azure SignalR will mitigate the issue. 

That does seem plausible, but do you think this theory holds up with what @anurse has mentioned? It seems a little bit suspicious that an issue with ANCM wouldn't be on present on VM's or Azure SignalR Service (though I don't know what stack the Azure SignalR Service is running on). 

Are there any logs from ANCM that would be able to confirm this  theory?

>The limit from the server to the service can be easily fixed and we should fix it.

Is this a quick fix that could be done in the next couple of days? Because, we're getting a lot of pressure to get this issue resolved as soon as possible, it would be great if I knew how far down the backlog this is. If it's going to be more than a week, I'm probably going to start removing SignalR as a plan C.

**Comment by davidfowl** [comment] 2018-06-22 18:18
> That does seem plausible, but do you think this theory holds up with what @anurse has mentioned? 

Yes. Those tests were done without IIS.

> It seems a little bit suspicious that an issue with ANCM wouldn't be on present on VM's or Azure SignalR Service (though I don't know what stack the Azure SignalR Service is running on).

The Azure SignalR Service does *NOT* use IIS (it's not even hosted on windows 😉).

>  Are there any logs from ANCM that would be able to confirm this theory?

HMMM, maybe http.sys logs but I'm not sure how much app service gives away. The right fix *is* to use the Azure SignalR service though. 

> Is this a quick fix that could be done in the next couple of days? Because, we're getting a lot of pressure to get this issue resolved as soon as possible, it would be great if I knew how far down the backlog this is. If it's going to be more than a week, I'm probably going to start removing SignalR as a plan C.

@chenkennt and @xscript would know better how long it takes fixes to be deployed but the fix hopefully isn't too bad. I'll discuss.

**Comment by stephenweaver** [comment] 2018-06-22 18:23
> Yes. Those tests were done without IIS.

👍 

>The Azure SignalR Service does NOT use IIS (it's not even hosted on windows 😉).

Kinda figured that. 💯 

> The right fix is to use the Azure SignalR service though.

That's plan A.

> @chenkennt and @xscript would know better how long it takes fixes to be deployed but the fix hopefully isn't too bad. I'll discuss.

Great, thanks!

**Comment by chenkennt** [comment] 2018-06-28 04:07
@stephenweaver we have decided to remove the size limit for sending from server to client. But you should expect poorer performance and longer latency when the message size goes bigger. This change is going to be rolled out later next week. I know you're in a very tight schedule, so please let me know whether this time works for you.

**Comment by xscript** [comment] 2018-08-03 08:32
@stephenweaver  Fix has been deployed to all instances. Please try again to double confirm.

**Closed by xscript** 2018-08-03 08:32 UTC
