### ISSUE TITLE
Ack-able message Microsoft.Azure.SignalR.Protocol.JoinGroupWithAckMessage timed out

### ISSUE THREAD

**Issue by AhsanKhan-Marn** [Azure/azure-signalr#1784] opened 2023-05-09 10:09 UTC
I faced connection drops for the SignalR client and I received these errors:

"Ack-able message Microsoft.Azure.SignalR.Protocol.JoinGroupWithAckMessage(ackId: 196215) timed out."
"Unable to write message to endpoint: {{URL of Service}}"

**Comment by vicancy** [comment] 2023-05-15 05:35
It could happen when the connection drops. And connection drop could happen when: service restarts, service maintenance, or network intermittent issues. Here contains more details of the explanation https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide#server_connection_drop.

In general, we recommend adding retry logic with TimeoutException when adding a connection to a group.

**Comment by AhsanKhan-Marn** [comment] 2023-05-16 08:15
Hello @vicancy 
We already have retry logic. It was not happening for a long time but now we again received these errors.

Today Also it's happening again and again as showing in Picture below

<img width="896" alt="image" src="https://github.com/Azure/azure-signalr/assets/133001826/39ad2d72-232e-4de8-95d1-b2cd10dc6832">

**Comment by vicancy** [comment] 2023-05-18 05:42
Could you email me `lianwei(at)microsoft.com` your resource id and the timestamps when such issues happen?

**Comment by AhsanKhan-Marn** [comment] 2023-05-18 07:18
Sent the email with required details

**Comment by AhsanKhan-Marn** [comment] 2023-05-21 10:02
@vicancy please see the email from `ahsan@marn.com`

**Comment by vicancy** [comment] 2023-05-30 01:34
> Hello @vicancy We already have retry logic. It was not happening for a long time but now we again received these errors.
> 
> Today Also it's happening again and again as showing in Picture below
> 
> <img alt="image" width="896" src="https://user-images.githubusercontent.com/133001826/238578695-39ad2d72-232e-4de8-95d1-b2cd10dc6832.png">

This issue is caused by app server thread starving with app server thread count peaks during those periods and then server connections were closed by "PingTimeout"

**Comment by vicancy** [comment] 2023-05-30 01:34
> We see this issue as soon as we upgrade from version 1.19.2 upwards. Going back to that version magically "resolves" this issue. Similar issue was reported in the past too #745


This one should be related to this fix https://github.com/Azure/azure-signalr/pull/1779 @KKhurin All the group messages are changed to be sticky to one server connection. We need improve the group sending logic, only the same group needs to sticky to one server connection.

**Comment by AhsanKhan-Marn** [comment] 2023-05-30 07:20
> > Hello @vicancy We already have retry logic. It was not happening for a long time but now we again received these errors.
> > Today Also it's happening again and again as showing in Picture below
> > <img alt="image" width="896" src="https://user-images.githubusercontent.com/133001826/238578695-39ad2d72-232e-4de8-95d1-b2cd10dc6832.png">
> 
> This issue is caused by app server thread starving with app server thread count peaks during those periods and then server connections were closed by "PingTimeout"

Yes, thanks for your support. I am following the suggestions you shared in your email. Also, I have removed the logic from OnDisconnectedAsync method which may cause thread starving

**Closed** 2023-10-26 06:21 UTC

**Comment by philip-reed** [comment] 2023-11-07 16:07
Also getting this issue, and wondered if there's any guidance that could be shared from the suggestions in the emails conversations you've had?

**Comment by vicancy** [comment] 2023-11-09 08:33
Many different scenarios can lead to this exception:
1. Server connection dropped around that period
2. A peak on such join/leave group requests
3. Heavy traffic that the server connection is unable to serve
4. Heavy traffic that the service is unable to serve
5. App server side high CPU or thread starvation https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide#thread-pool-starvation


The metrics and logs might give hints on the root cause.
