### ISSUE TITLE
Azure App service sticky session

### ISSUE THREAD

**Issue by BrennanConroy** [Azure/azure-signalr#1302] opened 2021-06-14 16:21 UTC
---
**Issue moved from dotnet/aspnetcore#33440**
- Please respond to @Zquiz.

---

_From @Zquiz on Thursday, June 10, 2021 6:53:05 PM_

Hello,
I hope someone can help or just tell me that's how it works. But we have moved our Blazor Serverside project from an on-premise hosted environment to using Azure App service.

If we try and use these settings

Autoscale when the memory hit x % usage (works)

Always on to true

ARR affinity off

Web sockets ON

Followed this documentation for this

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-5.0

We're always using an Azure SignalR Service as recommended by Mircosoft itself for this. Added Microsoft.Azure.SignalR.ServerStickyMode.Required; in our code, so it should be a sticky session.

The issue we're seeing is after 10-15 mins a browser fan will disconnect if the user is not on that fan but working on another
![image](https://user-images.githubusercontent.com/25593927/121580032-93aea480-ca2c-11eb-844c-4567716e5c43.png)

But if we enable ARR affinity cookies. Then it seems like it can negotiate just fine with SignalR. But we lose the effect of making people get onto a new instance if autoscale creates a new instance. So the load won't evenly be distributed.

Is it something we're doing wrong on our end or is it just some missed information for some failsafe built into SignalR?

Bonus info is that on-premise was we using Session sticky session LB and that worked fine for the most time.

Currently, auto-scaling to 9 instances in the morning to even out the load since the ARR cookie will let them stay on the instance for the whole workday.

Documentation I have been following
https://docs.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-5.0
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-5.0
https://docs.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-5.0

**Comment by BrennanConroy** [comment] 2021-06-14 16:21
---
**Issue moved from dotnet/aspnetcore#33440**
- Please respond to @BrennanConroy.

---

_From @BrennanConroy on Thursday, June 10, 2021 8:02:23 PM_

What is a browser fan? What version of Blazor are you using?
Are you saying that if you enable ARR affinity cookies the issue doesn't happen after 10-15 minutes?

**Comment by BrennanConroy** [comment] 2021-06-14 16:21
---
**Issue moved from dotnet/aspnetcore#33440**
- Please respond to @Zquiz.

---

_From @Zquiz on Thursday, June 10, 2021 8:09:11 PM_

It happens in all browsers that the users have available. So that's Chrome, Edge, Firefox all fully updated.
We're using the .NET 5 version of Blazor and all package is updated

Edit.
Yes with ARR affinity cookie enabled the user will only disconnect if I restart the app service.

**Comment by BrennanConroy** [comment] 2021-06-14 16:21
---
**Issue moved from dotnet/aspnetcore#33440**
- Please respond to @BrennanConroy.

---

_From @BrennanConroy on Thursday, June 10, 2021 8:19:43 PM_

Can you gather client side logs to see why the client disconnected

**Comment by BrennanConroy** [comment] 2021-06-14 16:21
---
**Issue moved from dotnet/aspnetcore#33440**
- Please respond to @Zquiz.

---

_From @Zquiz on Friday, June 11, 2021 11:31:09 AM_

Yeah sure.
Just the from SignalR or everything happen up to when the user disconnect?

**Comment by BrennanConroy** [comment] 2021-06-14 16:21
---
**Issue moved from dotnet/aspnetcore#33440**
- Please respond to @BrennanConroy.

---

_From @BrennanConroy on Friday, June 11, 2021 5:05:25 PM_

Ideally SignalR only, but we can probably parse out the other logs if it's not too bad. Also, debug or trace logs please.

**Comment by BrennanConroy** [comment] 2021-06-14 16:21
---
**Issue moved from dotnet/aspnetcore#33440**
- Please respond to @Zquiz.

---

_From @Zquiz on Monday, June 14, 2021 3:25:10 PM_

Sorry for the late delay.
not that easy to collect a live log while in the middle of moving from on premise to Azure and learn how to dump logs and so on.
Had to use the Live trace tool in Azure SignalR Service
![SignalRTrace002](https://user-images.githubusercontent.com/25593927/121911729-4e41ee00-cd30-11eb-98fb-16f46bd898c6.PNG)
![SignalRTrace001](https://user-images.githubusercontent.com/25593927/121911739-4eda8480-cd30-11eb-97c3-005f2a9a13f9.PNG)
If there is a better way to get the trace out in App Service please show us :)





<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/anlju/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/anlju/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





Id | Message | MessageTemplate | Level | TimeStamp | Exception | Properties | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp;
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
33390606 | Received message null for connection   "AdTghTJ49Xd8eAVzP3nJZQ865a96eb1" which does not exist. | Received message {tracingId} for connection {TransportConnectionId} which   does not exist. | Warning | 2021-06-14 16:21:32.020 | NULL | &lt;properties&gt;&lt;property   key='tracingId'&gt;&lt;/property&gt;&lt;property   key='TransportConnectionId'&gt;AdTghTJ49Xd8eAVzP3nJZQ865a96eb1&lt;/property&gt;&lt;property   key='EventId'&gt;&lt;structure type=''&gt;&lt;property   key='Id'&gt;10&lt;/property&gt;&lt;property   key='Name'&gt;ReceivedMessageForNonExistentConnection&lt;/property&gt;&lt;/structure&gt;&lt;/property&gt;&lt;property   key='SourceContext'&gt;Microsoft.Azure.SignalR.ServiceConnection&lt;/property&gt;&lt;/properties&gt;

**Comment by JialinXin** [comment] 2021-06-15 05:52
@Zquiz when you're using Azure SignalR service, App Service side "ARR affinity" and "Web Socket" settings are not required.

And if you're enabling auto-scale, when server is scale-down, related clients will be affected and disconnected. So it's likely to be an expected behavior. Please check if these things were happening together when you found the issues.

**Comment by Zquiz** [comment] 2021-06-15 12:25
Thanks for the reply.
Thanks for the clarification. Both in production and on our test environment is it happening after the auto scale has happened.
Even if I have set the scale out to 2 manual in test and wait 15 min afterward is it happening

**Comment by Zquiz** [comment] 2021-06-16 04:42
Silly question. Can this behavior be because of the healthcheck in the app service?

**Comment by JialinXin** [comment] 2021-06-16 05:32
It's not related to app service health check.

Client disconnect is by design if related server connection is dropped, like due to auto-scale or some server side connectivity issue. Basically with client auto [reconnect](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-5.0&tabs=visual-studio#automatically-reconnect) logic enabled, the impact in client would be minor. Clients will reconnect and route to a usable server connection. 

If you do care about client disconnect, please disable auto-scale for stability.
And if you want to have a graceful client migration logic, you can check with [GracefulShutdown](https://github.com/Azure/azure-signalr/blob/dev/docs/run-asp-net-core.md#gracefulshutdown) options.

**Comment by Zquiz** [comment] 2021-06-16 05:58
Okay. However this bahavior happens when no auto scaling is happening, but when the instans is higher than 1.
So I set this up for a test on our test app service to test if it was due to out scale down. But it wasn't

Setup
![image](https://user-images.githubusercontent.com/25593927/122164869-ad5e4a80-ce77-11eb-995c-caa56eff4ee2.png)
Waited 30 mins to make sure both instance was on and double checked with our app where I can see the instance name

![image](https://user-images.githubusercontent.com/25593927/122165003-daaaf880-ce77-11eb-9e31-c98993855c14.png)
Can see the instance name in our app and changed with every F5

![image](https://user-images.githubusercontent.com/25593927/122165071-f9a98a80-ce77-11eb-8f1f-809fedaa3d86.png)
The code to add SignalR with sticky session enabled and some other things to handle a issue with some document system.

![image](https://user-images.githubusercontent.com/25593927/122165123-0cbc5a80-ce78-11eb-9f66-60f58ada6e3e.png)
The setup in app service to what the documentation said to do.
And I still see the disconnect when not on that Browser tab after 10-15 mins.

If however I just turned on ARR affinity. Then it will stary connected till the user closes that tab. That's not ideal for us, since we got multiple instance between 6am till 8pm where most of the users are online. So is it some default timeout setting or just as designed when using Azure SignalR as backplane?

**Comment by JialinXin** [comment] 2021-06-16 06:08
The settings are for local hosted SignalR. When using Azure SignalR service, clients are connect to Azure SignalR service directly, so the ARR/Web sockets settings is not in use.

Would you share me your resourceId to let me(jixin[at]microsoft.com) have a further check?

**Comment by JialinXin** [comment] 2021-07-12 06:03
Offline synced that the issue is not applied to default Blazor Server template created project and should be related to customer's server side logic. So close the issue.

**Closed by JialinXin** 2021-07-12 06:03 UTC
